import { defineSlotRecipe } from "@pandacss/dev";

/** Neutral number input styles shared by the group and its stepper controls. */
export const numberFieldRecipe = defineSlotRecipe({
  className: "numberField",
  slots: [
    "root",
    "label",
    "group",
    "input",
    "increment",
    "decrement",
    "scrubArea",
    "scrubAreaCursor",
  ],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      minWidth: "12rem",
    },
    label: {
      color: "fg.default",
      fontSize: "sm",
      fontWeight: "700",
    },
    group: {
      alignItems: "stretch",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      display: "flex",
      overflow: "hidden",
      width: "100%",
      _focusWithin: {
        borderColor: "accent.default",
        boxShadow: "0 0 0 2px token(colors.focus.ring)",
      },
      _invalid: { borderColor: "danger" },
    },
    input: {
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "0",
      color: "fg.default",
      flex: "1",
      fontFamily: "system-ui, sans-serif",
      fontVariantNumeric: "tabular-nums",
      minWidth: "0",
      outline: "none",
      px: "3",
      py: "2",
      _focusVisible: {
        outline: "none",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    increment: {
      alignItems: "center",
      backgroundColor: "surface.subtle",
      borderColor: "border.default",
      borderStyle: "solid",
      borderWidth: "0",
      borderLeftWidth: "1px",
      borderRadius: "0",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      minWidth: "8",
      _hover: { backgroundColor: "surface.raised" },
      _focusVisible: {
        boxShadow: "inset 0 0 0 2px token(colors.focus.ring)",
        outline: "none",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    decrement: {
      alignItems: "center",
      backgroundColor: "surface.subtle",
      borderColor: "border.default",
      borderStyle: "solid",
      borderWidth: "0",
      borderRightWidth: "1px",
      borderRadius: "0",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      minWidth: "8",
      _hover: { backgroundColor: "surface.raised" },
      _focusVisible: {
        boxShadow: "inset 0 0 0 2px token(colors.focus.ring)",
        outline: "none",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    scrubArea: {
      color: "fg.muted",
      cursor: "ew-resize",
      fontSize: "xs",
      userSelect: "none",
    },
    scrubAreaCursor: {
      color: "accent.default",
      fontSize: "sm",
    },
  },
  variants: {
    size: {
      sm: { input: { fontSize: "sm", minHeight: "9" } },
      md: { input: { fontSize: "md", minHeight: "10" } },
      lg: { input: { fontSize: "lg", minHeight: "12" } },
    },
  },
  defaultVariants: { size: "md" },
  staticCss: ["*"],
});
