import { defineSlotRecipe } from "@pandacss/dev";

import { createBackdropBlurStyles } from "../../styles/backdrop";

export const dateRangePickerRecipe = defineSlotRecipe({
  className: "date-range-picker",
  slots: [
    "root",
    "label",
    "control",
    "trigger",
    "value",
    "clear",
    "close",
    "positioner",
    "popup",
    "header",
    "caption",
    "monthSelect",
    "yearSelect",
    "navigation",
    "calendar",
    "weekdays",
    "weekday",
    "grid",
    "day",
    "preview",
    "input",
  ],
  base: {
    root: { display: "flex", flexDirection: "column", gap: "2", width: "100%" },
    label: { color: "fg.default", fontSize: "sm", fontWeight: "600" },
    control: { alignItems: "center", display: "flex", gap: "2", width: "100%" },
    trigger: {
      alignItems: "center",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      justifyContent: "space-between",
      minHeight: "10",
      minWidth: "0",
      overflow: "hidden",
      px: "3",
      py: "2",
      textAlign: "left",
      width: "100%",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "2px" },
      _hover: { backgroundColor: "surface.subtle", borderColor: "border.strong" },
    },
    value: { minWidth: "0", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
    clear: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      height: "8",
      justifyContent: "center",
      width: "8",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "2px" },
      _hover: { backgroundColor: "surface.subtle", color: "fg.default" },
    },
    close: {
      alignSelf: "flex-end",
      backgroundColor: "accent.default",
      borderColor: "accent.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.onAccent",
      cursor: "pointer",
      minHeight: "9",
      minWidth: "5rem",
      maxWidth: "100%",
      px: "3",
      py: "2",
      whiteSpace: "nowrap",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "2px" },
      _hover: { backgroundColor: "accent.hover", borderColor: "accent.hover" },
    },
    positioner: { outline: "none", zIndex: "50" },
    popup: {
      ...createBackdropBlurStyles("md"),
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      color: "fg.default",
      minWidth: "80",
      maxWidth: "calc(100vw - 1rem)",
      overflow: "hidden",
      p: "4",
    },
    header: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      justifyContent: "space-between",
      marginBottom: "4",
    },
    caption: {
      flex: "1",
      fontSize: "sm",
      fontWeight: "700",
      textAlign: "center",
      textTransform: "capitalize",
    },
    monthSelect: {
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      fontSize: "sm",
      maxWidth: "10rem",
      minWidth: "0",
      px: "2",
      py: "1",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "1px" },
    },
    yearSelect: {
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      fontSize: "sm",
      maxWidth: "7rem",
      minWidth: "0",
      px: "2",
      py: "1",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "1px" },
    },
    navigation: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "lg",
      height: "8",
      justifyContent: "center",
      width: "8",
      _disabled: { cursor: "not-allowed", opacity: "0.45" },
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "2px" },
      _hover: { backgroundColor: "surface.subtle" },
    },
    calendar: { width: "100%" },
    weekdays: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      marginBottom: "1",
    },
    weekday: {
      color: "fg.muted",
      fontSize: "xs",
      fontWeight: "700",
      paddingBottom: "2",
      textAlign: "center",
      textTransform: "uppercase",
    },
    grid: { display: "grid", gridTemplateColumns: "repeat(7, minmax(0, 1fr))", rowGap: "1" },
    day: {
      alignItems: "center",
      aspectRatio: "1",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "sm",
      justifyContent: "center",
      minWidth: "8",
      outline: "none",
      position: "relative",
      width: "100%",
      _disabled: { cursor: "not-allowed", opacity: "0.4" },
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "-2px" },
      _hover: { backgroundColor: "surface.subtle" },
      "&[data-outside-month]": { color: "fg.muted", opacity: "0.65" },
      "&[data-range-start], &[data-range-end]": {
        backgroundColor: "accent.default",
        color: "fg.onAccent",
        fontWeight: "700",
      },
      "&[data-in-range]": { backgroundColor: "selected", borderRadius: "0" },
      "&[data-range-start]": { borderTopLeftRadius: "full", borderBottomLeftRadius: "full" },
      "&[data-range-end]": { borderTopRightRadius: "full", borderBottomRightRadius: "full" },
    },
    preview: { color: "fg.muted", fontSize: "sm", minHeight: "5" },
    input: {
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      minHeight: "9",
      minWidth: "0",
      px: "3",
      width: "100%",
      _focusVisible: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "1px",
      },
    },
  },
  staticCss: ["*"],
});
