import { defineSlotRecipe } from "@pandacss/dev";

import { createBackdropBlurStyles } from "../../styles/backdrop";

/**
 * Neutral zinc Popover slots. The recipe remains co-located with its
 * component and is registered by Panda during the package integration step.
 */
export const popoverRecipe = defineSlotRecipe({
  className: "popover",
  slots: ["trigger", "positioner", "popup", "title", "description", "close", "arrow"],
  base: {
    arrow: {
      ...createBackdropBlurStyles("md"),
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRightStyle: "solid",
      borderRightWidth: "1px",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      height: "2",
      transform: "rotate(45deg)",
      width: "2",
    },
    close: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xl",
      height: "8",
      justifyContent: "center",
      position: "absolute",
      right: "3",
      top: "3",
      transitionDuration: "normal",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      width: "8",
      _active: { transform: "scale(0.95)" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    description: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      lineHeight: "1.5",
      margin: "0",
    },
    popup: {
      ...createBackdropBlurStyles("md"),
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      color: "fg.default",
      maxWidth: "calc(100vw - 2rem)",
      boxSizing: "border-box",
      minWidth: "min(14rem, calc(100vw - 2rem))",
      overflow: "auto",
      overflowWrap: "anywhere",
      p: "4",
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.96)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.96)" },
    },
    positioner: {
      outline: "none",
      zIndex: "50",
    },
    title: {
      color: "fg.default",
      fontFamily: "system-ui, sans-serif",
      fontSize: "lg",
      fontWeight: "700",
      lineHeight: "1.5",
      margin: "0",
      paddingRight: "8",
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.interactive",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      gap: "2",
      justifyContent: "center",
      minHeight: "10",
      px: "3",
      py: "2",
      transitionDuration: "slow",
      transitionProperty: "background-color, border-color, box-shadow, color, transform",
      transitionTimingFunction: "standard",
      "&[data-popup-open]": { backgroundColor: "surface.subtle" },
      _active: { transform: "translateY(0)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", boxShadow: "lg", transform: "translateY(-1px)" },
    },
  },
  staticCss: ["*"],
});
