import { defineSlotRecipe } from "@pandacss/dev";

export const carouselRecipe = defineSlotRecipe({
  className: "carousel",
  slots: [
    "root",
    "viewport",
    "track",
    "item",
    "media",
    "caption",
    "title",
    "description",
    "control",
    "indicators",
    "indicator",
  ],
  base: {
    root: {
      minWidth: "0",
      position: "relative",
      width: "100%",
    },
    viewport: {
      overflow: "hidden",
      position: "relative",
      touchAction: "pan-y",
      width: "100%",
    },
    track: {
      display: "flex",
      transitionDuration: "normal",
      transitionProperty: "transform",
      transitionTimingFunction: "standard",
      willChange: "transform",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
    },
    item: {
      boxSizing: "border-box",
      flex: "0 0 100%",
      minWidth: "0",
      overflowWrap: "anywhere",
      position: "relative",
    },
    media: {
      minWidth: "0",
      overflow: "hidden",
      width: "100%",
      "& > *": { maxWidth: "100%" },
    },
    caption: {
      minWidth: "0",
      overflowWrap: "anywhere",
      paddingBlock: "3",
      paddingInline: "1",
    },
    title: { color: "fg.default", fontSize: "lg", fontWeight: "semibold", margin: "0" },
    description: { color: "fg.muted", fontSize: "sm", margin: "1 0 0" },
    control: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      height: "9",
      justifyContent: "center",
      position: "absolute",
      top: "40%",
      transform: "translateY(-50%)",
      width: "9",
      zIndex: "1",
      _focusVisible: { outline: "2px solid", outlineColor: "focus.ring", outlineOffset: "2px" },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    indicators: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      justifyContent: "center",
      padding: "3",
    },
    indicator: {
      appearance: "none",
      backgroundColor: "border.default",
      border: "0",
      borderRadius: "full",
      cursor: "pointer",
      height: "2",
      padding: "0",
      width: "2",
      _focusVisible: { outline: "2px solid", outlineColor: "focus.ring", outlineOffset: "2px" },
      _selected: { backgroundColor: "accent.default", width: "5" },
    },
  },
  variants: {
    orientation: {
      horizontal: {
        track: { flexDirection: "row" },
        control: { _first: { left: "2" }, _last: { right: "2" } },
      },
      vertical: {
        viewport: { touchAction: "pan-x" },
        track: { flexDirection: "column" },
        item: { flexBasis: "100%" },
        control: {
          left: "50%",
          top: "auto",
          transform: "translateX(-50%)",
          _first: { top: "2" },
          _last: { bottom: "2" },
        },
      },
    },
    active: { true: { item: { opacity: "1" } }, false: { item: { opacity: "0.9" } } },
  },
  defaultVariants: { orientation: "horizontal", active: true },
  staticCss: ["*"],
});
