import { defineSlotRecipe } from "@pandacss/dev";

export const carouselRecipe = defineSlotRecipe({
  className: "carousel",
  slots: [
    "root",
    "viewport",
    "track",
    "item",
    "media",
    "caption",
    "title",
    "description",
    "control",
    "indicators",
    "indicator",
  ],
  base: {
    root: {
      minWidth: "0",
      position: "relative",
      width: "100%",
    },
    viewport: {
      overflow: "hidden",
      position: "relative",
      touchAction: "pan-y",
      width: "100%",
    },
    track: {
      display: "flex",
      transitionDuration: "normal",
      transitionProperty: "transform",
      transitionTimingFunction: "standard",
      willChange: "transform",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
    },
    item: {
      boxSizing: "border-box",
      flex: "0 0 100%",
      minWidth: "0",
      overflowWrap: "anywhere",
      position: "relative",
    },
    media: {
      minWidth: "0",
      overflow: "hidden",
      width: "100%",
      "& > *": { maxWidth: "100%" },
    },
    caption: {
      minWidth: "0",
      overflowWrap: "anywhere",
      paddingBlock: "3",
      paddingInline: "1",
    },
    title: { color: "fg.default", fontSize: "lg", fontWeight: "semibold", margin: "0" },
    description: { color: "fg.muted", fontSize: "sm", margin: "1 0 0" },
    control: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      height: "9",
      justifyContent: "center",
      position: "absolute",
      top: "40%",
      transform: "translateY(-50%)",
      width: "9",
      zIndex: "1",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "2px" },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    indicators: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      justifyContent: "center",
      padding: "3",
    },
    indicator: {
      appearance: "none",
      backgroundColor: "border.default",
      border: "0",
      borderRadius: "full",
      cursor: "pointer",
      height: "2",
      padding: "0",
      width: "2",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "2px" },
      _selected: { backgroundColor: "accent.default", width: "5" },
    },
  },
  variants: {
    orientation: {
      horizontal: {
        root: {
          "& [data-slot='carousel-previous']": { left: "2" },
          "& [data-slot='carousel-next']": { right: "2" },
        },
        track: { flexDirection: "row" },
        indicators: {
          backgroundColor: "surface.raised",
          backdropBlur: "sm",
          backdropFilter: "auto",
          borderColor: "border.default",
          borderRadius: "lg",
          borderStyle: "solid",
          borderWidth: "1px",
          gap: "2",
          marginInline: "auto",
          padding: "2",
          width: "fit-content",
          boxShadow: "sm",
        },
      },
      vertical: {
        root: {
          boxSizing: "border-box",
          display: "flex",
          flexDirection: "column",
          height: "100%",
          minHeight: "0",
          paddingInlineEnd: "12",
          "& [data-slot='carousel-previous']": { top: "2" },
          "& [data-slot='carousel-next']": { bottom: "2" },
        },
        viewport: { flex: "1 1 0%", minHeight: "0", touchAction: "pan-x" },
        track: { flexDirection: "column", height: "100%" },
        item: {
          display: "flex",
          flexBasis: "100%",
          flexDirection: "column",
          height: "100%",
          minHeight: "0",
        },
        media: {
          alignItems: "center",
          display: "flex",
          flex: "1 1 auto",
          justifyContent: "center",
          minHeight: "0",
          width: "100%",
          "& > *": { maxHeight: "100%" },
          "& img": { height: "auto", maxHeight: "100%", maxWidth: "100%", objectFit: "contain" },
        },
        caption: { flex: "0 0 auto", paddingBottom: "12", width: "100%" },
        indicators: {
          backgroundColor: "surface.raised",
          backdropBlur: "sm",
          backdropFilter: "auto",
          borderColor: "border.default",
          borderRadius: "lg",
          borderStyle: "solid",
          borderWidth: "1px",
          flexDirection: "column",
          gap: "2",
          padding: "2",
          position: "absolute",
          right: "2",
          boxShadow: "sm",
          top: "50%",
          transform: "translateY(-50%)",
          zIndex: "1",
        },
        indicator: {
          height: "2",
          width: "2",
          _selected: { height: "5", width: "2" },
        },
        control: {
          left: "50%",
          top: "auto",
          transform: "translateX(-50%)",
        },
      },
    },
    active: { true: { item: { opacity: "1" } }, false: { item: { opacity: "0.9" } } },
  },
  defaultVariants: { orientation: "horizontal", active: true },
  staticCss: ["*"],
});
