import { defineSlotRecipe } from "@pandacss/dev";

export const dataToolbarRecipe = defineSlotRecipe({
  className: "data-toolbar",
  slots: [
    "root",
    "search",
    "filters",
    "sort",
    "selection",
    "clearSelection",
    "actions",
    "clear",
    "separator",
  ],
  base: {
    root: {
      alignItems: "center",
      display: "flex",
      flexWrap: "wrap",
      gap: "2",
      minWidth: "0",
      width: "100%",
    },
    search: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      flex: "1 1 14rem",
      minHeight: "10",
      minWidth: "10rem",
      outline: "none",
      px: "3",
      py: "2",
      _focusVisible: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "1px",
      },
    },
    filters: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: "2", minWidth: "0" },
    sort: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      maxWidth: "100%",
      minHeight: "10",
      minWidth: "9rem",
      outline: "none",
      px: "3",
      py: "2",
      _focusVisible: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "1px",
      },
    },
    selection: {
      alignItems: "center",
      display: "inline-flex",
      flexWrap: "wrap",
      gap: "2",
      minWidth: "0",
    },
    clearSelection: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      color: "accent.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "sm",
      minHeight: "8",
      px: "2",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "1px" },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    actions: {
      alignItems: "center",
      display: "inline-flex",
      flexWrap: "wrap",
      gap: "2",
      marginInlineStart: "auto",
    },
    clear: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      minHeight: "8",
      px: "2",
      _focusVisible: { outline: "2px solid", outlineColor: "focus", outlineOffset: "1px" },
      _hover: { backgroundColor: "surface.subtle", color: "fg.default" },
    },
    separator: { backgroundColor: "border.default", flexShrink: "0", height: "6", width: "1px" },
  },
  staticCss: ["*"],
});
