import { defineSlotRecipe } from "@pandacss/dev";

import { createBackdropBlurStyles } from "../../styles/backdrop";

export const colorPickerRecipe = defineSlotRecipe({
  className: "color-picker",
  slots: [
    "root",
    "label",
    "control",
    "trigger",
    "preview",
    "value",
    "positioner",
    "popup",
    "palette",
    "paletteIndicator",
    "hue",
    "alpha",
    "swatches",
    "swatch",
    "input",
    "nativeInput",
  ],
  base: {
    root: {
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      width: "100%",
    },
    label: { color: "fg.default", fontSize: "sm", fontWeight: "700" },
    control: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      width: "100%",
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      cursor: "pointer",
      display: "inline-flex",
      gap: "2",
      minHeight: "10",
      maxWidth: "100%",
      minWidth: "0",
      padding: "2",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "2px" },
      _hover: { borderColor: "border.strong" },
    },
    preview: {
      borderRadius: "md",
      boxShadow: "sm",
      display: "inline-block",
      height: "6",
      width: "6",
    },
    value: {
      color: "fg.muted",
      flex: "1",
      fontFamily: "monospace",
      fontSize: "sm",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    positioner: { zIndex: "10" },
    popup: {
      ...createBackdropBlurStyles("md"),
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "lg",
      boxSizing: "border-box",
      display: "flex",
      flexDirection: "column",
      gap: "3",
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "0",
      padding: "4",
      width: "min(20rem, calc(100vw - 2rem))",
    },
    palette: {
      borderRadius: "lg",
      cursor: "crosshair",
      height: "40",
      maxWidth: "100%",
      overflow: "hidden",
      position: "relative",
      touchAction: "none",
      width: "100%",
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "2px" },
    },
    paletteIndicator: {
      backgroundColor: "transparent",
      borderColor: "white",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "2px",
      boxShadow: "0 0 0 1px rgba(0, 0, 0, 0.65)",
      height: "5",
      left: "var(--jaci-color-palette-saturation)",
      pointerEvents: "none",
      position: "absolute",
      top: "var(--jaci-color-palette-lightness)",
      transform: "translate(-50%, -50%)",
      width: "5",
    },
    hue: {
      accentColor: "accent.default",
      boxSizing: "border-box",
      maxWidth: "100%",
      width: "100%",
    },
    alpha: {
      accentColor: "accent.default",
      boxSizing: "border-box",
      maxWidth: "100%",
      width: "100%",
    },
    swatches: {
      border: "0",
      display: "flex",
      flexWrap: "wrap",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      margin: "0",
      padding: "0",
    },
    swatch: {
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "2px",
      cursor: "pointer",
      height: "7",
      padding: "0",
      width: "7",
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "2px" },
      _hover: { transform: "scale(1.08)" },
    },
    input: {
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      fontFamily: "monospace",
      minHeight: "9",
      paddingInline: "3",
      maxWidth: "100%",
      minWidth: "0",
      width: "100%",
      _focus: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "accent.default",
      },
      "&[aria-invalid='true']": { borderColor: "danger" },
    },
    nativeInput: {
      accentColor: "accent.default",
      boxSizing: "border-box",
      maxWidth: "100%",
      minHeight: "9",
      minWidth: "0",
      width: "100%",
    },
  },
  staticCss: ["*"],
});
