import { defineSlotRecipe } from "@pandacss/dev";

export const treeViewRecipe = defineSlotRecipe({
  className: "tree-view",
  slots: ["root", "itemWrapper", "item", "group", "toggle", "label", "loading", "empty", "error"],
  base: {
    root: {
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      gap: "1",
      outline: "0",
      width: "100%",
    },
    itemWrapper: {
      display: "flex",
      flexDirection: "column",
      minWidth: "0",
      outline: "0",
      width: "100%",
      "&:focus-visible > [data-slot='tree-view-item-row']": {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "1px",
      },
    },
    item: {
      alignItems: "center",
      color: "fg.default",
      borderRadius: "md",
      cursor: "pointer",
      display: "flex",
      flexWrap: "wrap",
      gap: "2",
      minHeight: "9",
      outline: "0",
      px: "2",
      py: "1",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      _hover: { backgroundColor: "surface.subtle" },
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "1px" },
      "&[data-selected]": { backgroundColor: "surface.subtle", color: "accent.default" },
      "&[data-disabled]": { cursor: "not-allowed", opacity: "0.5" },
    },
    group: {
      backgroundColor: "surface.canvas",
      color: "fg.default",
      flexBasis: "100%",
      display: "flex",
      flexDirection: "column",
      gap: "1",
      marginInlineStart: "5",
      minWidth: "0",
      paddingInlineStart: "2",
      width: "100%",
    },
    toggle: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "sm",
      height: "6",
      justifyContent: "center",
      p: "0",
      width: "6",
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "1px" },
      _disabled: { cursor: "not-allowed" },
    },
    label: {
      flex: "1",
      minWidth: "0",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    loading: { color: "fg.muted", fontSize: "sm", padding: "2" },
    empty: { color: "fg.muted", fontSize: "sm", padding: "2" },
    error: { color: "danger", fontSize: "sm", padding: "2" },
  },
  staticCss: ["*"],
});
