import { defineSlotRecipe } from "@pandacss/dev";

export const copyableRecipe = defineSlotRecipe({
  className: "copyable",
  slots: ["root", "content", "indicator", "status"],
  base: {
    root: {
      alignItems: "center",
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      gap: "3",
      justifyContent: "space-between",
      maxWidth: "100%",
      minWidth: "0",
      paddingBlock: "2",
      paddingInline: "3",
      textAlign: "start",
      transitionDuration: "fast",
      transitionProperty: "background-color, border-color, color, opacity",
      transitionTimingFunction: "standard",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      "&[data-copied]": { borderColor: "success", color: "success" },
    },
    content: {
      flex: "1",
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      fontSize: "sm",
      minWidth: "0",
      overflowWrap: "anywhere",
      whiteSpace: "pre-wrap",
    },
    indicator: {
      color: "fg.muted",
      flexShrink: "0",
      fontSize: "xs",
      fontWeight: "600",
      whiteSpace: "nowrap",
      "&[data-copied]": { color: "success" },
    },
    status: {
      border: "0",
      clip: "rect(0 0 0 0)",
      height: "1px",
      margin: "-1px",
      overflow: "hidden",
      padding: "0",
      position: "absolute",
      whiteSpace: "nowrap",
      width: "1px",
    },
  },
  staticCss: ["*"],
});
