import { defineSlotRecipe } from "@pandacss/dev";

export const datePickerRecipe = defineSlotRecipe({
  className: "date-picker",
  slots: [
    "root",
    "label",
    "control",
    "trigger",
    "value",
    "clear",
    "positioner",
    "popup",
    "header",
    "caption",
    "navigation",
    "calendar",
    "weekdays",
    "weekday",
    "grid",
    "day",
  ],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      width: "100%",
    },
    label: {
      color: "fg.default",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      lineHeight: "1.5",
    },
    control: {
      alignItems: "center",
      display: "flex",
      position: "relative",
      width: "100%",
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      gap: "2",
      justifyContent: "space-between",
      minHeight: "10",
      overflow: "hidden",
      px: "3",
      py: "2",
      textAlign: "left",
      transitionDuration: "normal",
      transitionProperty: "background-color, border-color, box-shadow",
      transitionTimingFunction: "standard",
      width: "100%",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", borderColor: "border.strong" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    value: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    clear: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "lg",
      height: "6",
      justifyContent: "center",
      lineHeight: "1",
      width: "6",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", color: "fg.default" },
    },
    positioner: { outline: "none", zIndex: "50" },
    popup: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      color: "fg.default",
      minWidth: "80",
      p: "4",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.96)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.96)" },
    },
    header: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      justifyContent: "space-between",
      marginBottom: "4",
    },
    caption: {
      flex: "1",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "700",
      textAlign: "center",
      textTransform: "capitalize",
    },
    navigation: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "lg",
      height: "8",
      justifyContent: "center",
      width: "8",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.45" },
    },
    calendar: {
      width: "100%",
    },
    weekdays: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      marginBottom: "1",
    },
    weekday: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xs",
      fontWeight: "700",
      paddingBottom: "2",
      textAlign: "center",
      textTransform: "uppercase",
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      rowGap: "1",
    },
    day: {
      alignItems: "center",
      aspectRatio: "1",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      justifyContent: "center",
      minWidth: "8",
      outline: "none",
      position: "relative",
      width: "100%",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.4" },
      "&[data-selected]": {
        backgroundColor: "accent.default",
        color: "fg.onAccent",
        fontWeight: "700",
        _hover: { backgroundColor: "accent.hover" },
      },
      "&[data-outside-month]": { color: "fg.muted", opacity: "0.65" },
      "&[data-today]": { fontWeight: "700" },
    },
  },
  variants: {
    size: {
      sm: {
        trigger: { fontSize: "sm", minHeight: "9", px: "2", py: "1" },
        day: { fontSize: "xs", minWidth: "7" },
      },
      md: {},
      lg: {
        trigger: { fontSize: "md", minHeight: "12", px: "4", py: "3" },
        day: { fontSize: "md", minWidth: "10" },
      },
    },
  },
  defaultVariants: { size: "md" },
  staticCss: ["*"],
});
