import { defineSlotRecipe } from "@pandacss/dev";

export const calendarRecipe = defineSlotRecipe({
  className: "calendar",
  slots: [
    "root",
    "header",
    "caption",
    "navigation",
    "monthSelect",
    "yearSelect",
    "calendar",
    "weekdays",
    "weekday",
    "grid",
    "day",
  ],
  base: {
    root: {
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      gap: "3",
      minWidth: "18rem",
      width: "100%",
    },
    header: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      justifyContent: "space-between",
    },
    caption: {
      flex: "1",
      fontSize: "sm",
      fontWeight: "700",
      textAlign: "center",
      textTransform: "capitalize",
    },
    navigation: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "lg",
      height: "8",
      justifyContent: "center",
      width: "8",
      _disabled: { cursor: "not-allowed", opacity: "0.45" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    monthSelect: {
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      fontSize: "sm",
      fontWeight: "600",
      maxWidth: "10rem",
      minWidth: "0",
      outline: "none",
      px: "2",
      py: "1",
      _focusVisible: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "1px",
      },
    },
    yearSelect: {
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      fontSize: "sm",
      fontWeight: "600",
      maxWidth: "7rem",
      minWidth: "0",
      outline: "none",
      px: "2",
      py: "1",
      _focusVisible: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "1px",
      },
    },
    calendar: { width: "100%" },
    weekdays: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      marginBottom: "1",
    },
    weekday: {
      color: "fg.muted",
      fontSize: "xs",
      fontWeight: "700",
      paddingBottom: "2",
      textAlign: "center",
      textTransform: "uppercase",
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "repeat(7, minmax(0, 1fr))",
      rowGap: "1",
    },
    day: {
      alignItems: "center",
      aspectRatio: "1",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "sm",
      justifyContent: "center",
      minWidth: "8",
      outline: "none",
      position: "relative",
      width: "100%",
      _disabled: { cursor: "not-allowed", opacity: "0.4" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "focus",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      "&[data-outside-month]": { color: "fg.muted", opacity: "0.65" },
      "&[data-selected]": {
        backgroundColor: "accent.default",
        color: "fg.onAccent",
        fontWeight: "700",
        _hover: { backgroundColor: "accent.hover" },
      },
      "&[data-today]": { boxShadow: "inset 0 0 0 1px token(colors.accent.default)" },
    },
  },
  staticCss: ["*"],
});
