import { defineSlotRecipe } from "@pandacss/dev";

export const navigationMenuRecipe = defineSlotRecipe({
  className: "navigation-menu",
  slots: [
    "root",
    "list",
    "item",
    "trigger",
    "content",
    "link",
    "icon",
    "positioner",
    "viewport",
    "popup",
    "backdrop",
    "arrow",
  ],
  base: {
    root: { color: "fg.default", position: "relative", width: "100%" },
    list: {
      alignItems: "center",
      display: "flex",
      gap: "1",
      listStyle: "none",
      margin: "0",
      padding: "1",
    },
    item: { position: "relative" },
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "inherit",
      fontSize: "sm",
      fontWeight: "600",
      gap: "2",
      minHeight: "9",
      px: "3",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      _hover: { backgroundColor: "surface.subtle" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      "&[data-popup-open]": { backgroundColor: "surface.subtle" },
    },
    content: {
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "0",
      overflowWrap: "anywhere",
      padding: "3",
      width: "min(32rem, calc(100vw - 2rem))",
    },
    link: {
      borderRadius: "md",
      color: "fg.default",
      display: "block",
      fontSize: "sm",
      px: "3",
      py: "2",
      textDecoration: "none",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      _hover: { backgroundColor: "surface.subtle", color: "link.hover" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      "&[data-active]": { backgroundColor: "surface.subtle", color: "accent.hover" },
    },
    icon: { color: "fg.muted", display: "inline-flex", transitionDuration: "fast" },
    positioner: { zIndex: "10" },
    viewport: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "lg",
      overflow: "hidden",
      // Do not use `display: none` here. The viewport is part of Base UI's
      // dismissal/floating interaction tree; removing it from the layout can
      // prevent pointer-leave and outside-press events from reaching the
      // primitive. Base UI controls the content visibility itself.
      "&[data-open=false]": {
        borderWidth: "0",
        height: "0",
        minHeight: "0",
        pointerEvents: "none",
        visibility: "hidden",
      },
    },
    popup: {
      backgroundColor: "surface.raised",
      color: "fg.default",
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "0",
      overflow: "auto",
      overflowWrap: "anywhere",
    },
    backdrop: { backgroundColor: "surface.overlay", inset: "0", position: "fixed" },
    arrow: { fill: "surface.raised" },
  },
  variants: {
    orientation: {
      horizontal: {
        root: { width: "fit-content" },
        list: { flexDirection: "row" },
      },
      vertical: {
        list: { alignItems: "stretch", flexDirection: "column" },
        trigger: { justifyContent: "space-between", width: "100%" },
      },
    },
  },
  defaultVariants: { orientation: "horizontal" },
  staticCss: ["*"],
});
