import { defineSlotRecipe } from "@pandacss/dev";

export const stepperRecipe = defineSlotRecipe({
  className: "stepper",
  slots: [
    "root",
    "list",
    "item",
    "trigger",
    "indicator",
    "title",
    "description",
    "content",
    "separator",
    "previous",
    "next",
  ],
  base: {
    root: {
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      gap: "4",
      minWidth: "0",
      width: "100%",
    },
    list: {
      display: "flex",
      gap: "0",
      listStyle: "none",
      margin: "0",
      minWidth: "0",
      padding: "0",
      width: "100%",
    },
    item: {
      display: "flex",
      flex: "1",
      minWidth: "0",
      position: "relative",
    },
    trigger: {
      alignItems: "start",
      backgroundColor: "transparent",
      border: "0",
      color: "fg.muted",
      cursor: "pointer",
      display: "grid",
      flex: "1",
      columnGap: "2",
      rowGap: "1",
      gridTemplateColumns: "2rem minmax(0, 1fr)",
      gridTemplateRows: "auto auto",
      minWidth: "0",
      padding: "0",
      textAlign: "left",
      width: "100%",
      transitionDuration: "normal",
      transitionProperty: "color, opacity",
      transitionTimingFunction: "standard",
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
      _focusVisible: {
        borderRadius: "md",
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      "& > [data-slot=stepper-indicator]": {
        gridColumn: "1",
        gridRow: "1 / span 2",
        position: "relative",
        zIndex: "1",
      },
      "& > [data-slot=stepper-title]": { gridColumn: "2" },
      "& > [data-slot=stepper-description]": { gridColumn: "2" },
      "& > span:not([data-slot])": {
        display: "flex",
        flexDirection: "column",
        gridColumn: "2",
        minWidth: "0",
      },
      "&[data-status=current]": { color: "fg.default" },
      "&[data-status=complete]": { color: "accent.default" },
      "&[data-status=disabled]": { color: "fg.muted", cursor: "not-allowed", opacity: "0.55" },
    },
    indicator: {
      alignItems: "center",
      backgroundColor: "surface.default",
      borderColor: "border.strong",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.muted",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "xs",
      fontWeight: "700",
      height: "8",
      justifyContent: "center",
      lineHeight: "1",
      width: "8",
      "&[data-status=current]": {
        backgroundColor: "accent.default",
        borderColor: "accent.default",
        color: "fg.onAccent",
      },
      "&[data-status=complete]": {
        backgroundColor: "accent.default",
        borderColor: "accent.default",
        color: "fg.onAccent",
      },
      "&[data-status=disabled]": { opacity: "0.55" },
    },
    title: {
      display: "block",
      fontSize: "sm",
      fontWeight: "700",
      lineHeight: "1.35",
      minWidth: "0",
      overflow: "hidden",
      overflowWrap: "anywhere",
      textOverflow: "ellipsis",
    },
    description: {
      color: "fg.muted",
      display: "block",
      fontSize: "xs",
      lineHeight: "1.35",
      minWidth: "0",
      overflowWrap: "anywhere",
    },
    content: {
      color: "fg.default",
      minWidth: "0",
      paddingTop: "4",
      width: "100%",
      "&[hidden]": { display: "none" },
    },
    separator: {
      backgroundColor: "border.default",
      flex: "1",
      height: "1px",
      marginInline: "3",
      minWidth: "1rem",
      position: "relative",
      top: "1rem",
    },
    previous: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.interactive",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      maxWidth: "100%",
      minWidth: "0",
      paddingInline: "3",
      paddingBlock: "2",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "2px" },
      _hover: { backgroundColor: "surface.subtle" },
    },
    next: {
      alignItems: "center",
      backgroundColor: "accent.default",
      border: "0",
      borderRadius: "lg",
      color: "fg.onAccent",
      cursor: "pointer",
      display: "inline-flex",
      justifyContent: "center",
      maxWidth: "100%",
      minWidth: "0",
      paddingInline: "3",
      paddingBlock: "2",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "2px" },
      _hover: { backgroundColor: "accent.hover" },
    },
  },
  variants: {
    orientation: {
      horizontal: {
        list: { alignItems: "flex-start", flexDirection: "row" },
        item: {
          alignItems: "flex-start",
          flexDirection: "column",
          paddingInlineEnd: "4",
        },
        separator: {
          left: "2rem",
          margin: "0",
          position: "absolute",
          right: "0",
          top: "1rem",
          width: "auto",
        },
      },
      vertical: {
        list: { flexDirection: "column" },
        item: { alignItems: "stretch", flexDirection: "column" },
        trigger: { alignItems: "start" },
        separator: {
          height: "1.5rem",
          marginInlineStart: "1rem",
          marginInlineEnd: "0",
          marginBlock: "1",
          width: "1px",
        },
      },
    },
    status: {
      current: {},
      complete: {},
      upcoming: {},
      disabled: {},
    },
  },
  defaultVariants: { orientation: "horizontal", status: "upcoming" },
  staticCss: ["*"],
});
