import { defineSlotRecipe } from "@pandacss/dev";

export const comboboxRecipe = defineSlotRecipe({
  className: "combobox",
  slots: [
    "root",
    "label",
    "inputGroup",
    "input",
    "trigger",
    "icon",
    "value",
    "positioner",
    "popup",
    "list",
    "item",
    "itemIndicator",
    "group",
    "groupLabel",
    "empty",
    "loading",
    "clear",
    "status",
    "arrow",
  ],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      width: "100%",
    },
    label: {
      color: "fg.default",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "700",
      lineHeight: "1.5",
    },
    inputGroup: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "2px",
      boxSizing: "border-box",
      display: "flex",
      gap: "1",
      minHeight: "10",
      paddingInline: "3",
      transitionDuration: "slow",
      transitionProperty: "border-color, box-shadow",
      transitionTimingFunction: "standard",
      maxWidth: "100%",
      minWidth: "0",
      width: "100%",
      _focusWithin: {
        borderColor: "accent.default",
        boxShadow: "sm",
      },
      _hover: { borderColor: "border.strong" },
      "&[data-invalid]": { borderColor: "danger" },
      "&[data-popup-open]": { borderColor: "accent.default" },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    input: {
      backgroundColor: "transparent",
      border: "0",
      color: "fg.default",
      flex: "1",
      fontFamily: "system-ui, sans-serif",
      fontSize: { base: "sm", lg: "md" },
      minWidth: "0",
      outline: "none",
      py: "2",
      width: "100%",
      _placeholder: { color: "fg.muted" },
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      boxSizing: "border-box",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "lg",
      height: "8",
      justifyContent: "center",
      maxWidth: "100%",
      minWidth: "0",
      width: "8",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { color: "fg.default" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    icon: {
      color: "fg.muted",
      flexShrink: "0",
      fontSize: "lg",
      lineHeight: "1",
      "&[data-popup-open]": { color: "accent.default", transform: "rotate(180deg)" },
    },
    value: {
      color: "fg.default",
      fontSize: "sm",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    positioner: { outline: "none", zIndex: "50" },
    popup: {
      backdropBlur: "md",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      boxSizing: "border-box",
      color: "fg.default",
      maxHeight: "var(--available-height)",
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "0",
      overflow: "hidden",
      p: "2",
      transformOrigin: "var(--transform-origin)",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: "min(var(--anchor-width, 100%), calc(100vw - 2rem))",
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.96)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.96)" },
    },
    list: {
      display: "flex",
      flexDirection: "column",
      gap: "1",
      maxHeight: "var(--available-height)",
      overflowY: "auto",
      overscrollBehavior: "contain",
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "lg",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      gap: "2",
      justifyContent: "flex-start",
      minHeight: "9",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      px: "3",
      py: "2",
      textAlign: "left",
      transitionDuration: "normal",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      width: "100%",
      "&[data-highlighted]": { backgroundColor: "surface.subtle" },
      "&[data-selected]": { backgroundColor: "accent.default", color: "fg.onAccent" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    itemIndicator: {
      color: "currentColor",
      flexShrink: "0",
      fontSize: "sm",
      lineHeight: "1",
      marginInlineStart: "auto",
    },
    group: { display: "flex", flexDirection: "column", gap: "1" },
    groupLabel: {
      color: "fg.muted",
      fontSize: "xs",
      fontWeight: "700",
      letterSpacing: "wide",
      pb: "1",
      pt: "2",
      px: "3",
      textTransform: "uppercase",
    },
    empty: {
      color: "fg.muted",
      fontSize: "sm",
      p: "3",
      textAlign: "center",
    },
    loading: { color: "fg.muted", fontSize: "sm", p: "3", textAlign: "center" },
    clear: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "lg",
      height: "7",
      justifyContent: "center",
      width: "7",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", color: "fg.default" },
    },
    status: { color: "fg.muted", fontSize: "sm" },
    arrow: {
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRightStyle: "solid",
      borderRightWidth: "1px",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      height: "2",
      transform: "rotate(45deg)",
      width: "2",
    },
  },
  variants: {
    size: {
      sm: {
        inputGroup: { minHeight: "9", paddingInline: "2" },
        input: { fontSize: "sm", py: "1" },
      },
      md: {},
      lg: {
        inputGroup: { minHeight: "12", paddingInline: "4" },
        input: { fontSize: "lg", py: "3" },
      },
    },
  },
  defaultVariants: { size: "md" },
  staticCss: ["*"],
});
