import { defineSlotRecipe } from "@pandacss/dev";

export const toolbarRecipe = defineSlotRecipe({
  className: "toolbar",
  slots: ["root", "group", "button", "link", "input", "separator"],
  base: {
    root: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      minWidth: "0",
      padding: "2",
      "&[data-orientation='vertical']": { alignItems: "stretch", flexDirection: "column" },
    },
    group: {
      alignItems: "center",
      display: "flex",
      gap: "1",
      minWidth: "0",
      "&[data-orientation='vertical']": { alignItems: "stretch", flexDirection: "column" },
    },
    button: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "transparent",
      borderColor: "transparent",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "sm",
      fontWeight: "600",
      gap: "2",
      justifyContent: "center",
      minHeight: "9",
      paddingInline: "3",
      transitionDuration: "fast",
      transitionProperty: "background-color, border-color, color, opacity",
      transitionTimingFunction: "standard",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    link: {
      alignItems: "center",
      borderRadius: "md",
      color: "link.default",
      display: "inline-flex",
      fontSize: "sm",
      minHeight: "9",
      paddingInline: "2",
      textDecoration: "none",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { color: "link.hover", textDecoration: "underline" },
    },
    input: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "md",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      fontSize: "sm",
      minHeight: "9",
      minWidth: "10rem",
      outline: "none",
      paddingInline: "3",
      _focus: { borderColor: "accent.default" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    separator: {
      backgroundColor: "border.default",
      flexShrink: "0",
      height: "1.25rem",
      width: "1px",
      "&[data-orientation='horizontal']": { height: "1px", width: "100%" },
    },
  },
  variants: {
    variant: {
      solid: {
        button: { backgroundColor: "surface.default", borderColor: "border.default" },
      },
      outline: {
        button: { backgroundColor: "transparent", borderColor: "border.default" },
      },
      ghost: {
        button: { backgroundColor: "transparent", borderColor: "transparent" },
      },
    },
    size: {
      sm: { button: { fontSize: "xs", minHeight: "8", paddingInline: "2" } },
      md: { button: { fontSize: "sm", minHeight: "9", paddingInline: "3" } },
      lg: { button: { fontSize: "md", minHeight: "10", paddingInline: "4" } },
    },
  },
  defaultVariants: {
    size: "md",
    variant: "ghost",
  },
  staticCss: ["*"],
});
