import { defineRecipe, defineSlotRecipe } from "@pandacss/dev";

export const headingRecipe = defineRecipe({
  className: "heading",
  base: {
    alignItems: "center",
    color: "fg.default",
    display: "flex",
    fontWeight: "700",
    gap: "1",
    lineHeight: "1.5",
  },
  variants: {
    size: {
      xs: { fontSize: { base: "md", md: "md", lg: "lg" } },
      sm: { fontSize: { base: "md", md: "lg", lg: "xl" } },
      md: { fontSize: { base: "lg", md: "xl", lg: "2xl" } },
      lg: { fontSize: { base: "xl", md: "2xl", lg: "3xl" } },
      xl: { fontSize: { base: "2xl", md: "3xl", lg: "4xl" } },
      "2xl": { fontSize: { base: "3xl", md: "4xl", lg: "5xl" } },
    },
  },
  defaultVariants: {
    size: "md",
  },
  staticCss: ["*"],
});

export const textRecipe = defineRecipe({
  className: "text",
  base: {
    color: "fg.default",
    fontFamily: "system-ui, sans-serif",
    lineHeight: "1.5",
  },
  variants: {
    size: {
      sm: { fontSize: "sm" },
      md: { fontSize: "md" },
      lg: { fontSize: "lg" },
    },
    tone: {
      default: { color: "fg.default" },
      muted: { color: "fg.muted" },
    },
  },
  defaultVariants: {
    size: "md",
    tone: "default",
  },
  staticCss: ["*"],
});

export const paragraphRecipe = defineRecipe({
  className: "paragraph",
  base: {
    color: "fg.default",
    display: "inline-block",
    fontFamily: "system-ui, sans-serif",
    fontSize: "xl",
    lineHeight: "1.5",
    marginBlock: "2",
    textAlign: "justify",
    textIndent: { base: "5", md: "10" },
  },
  staticCss: ["*"],
});

export const linkRecipe = defineRecipe({
  className: "link",
  base: {
    color: "link.default",
    textDecoration: "none",
    transitionDuration: "slow",
    transitionTimingFunction: "standard",
    _hover: { color: "link.hover" },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.default",
      outlineOffset: "2px",
    },
  },
  variants: {
    subtle: {
      false: {
        color: "accent.default",
        textDecoration: "underline",
        textUnderlineOffset: "3px",
        _hover: { color: "accent.hover" },
      },
      true: {},
    },
  },
  defaultVariants: {
    subtle: true,
  },
  staticCss: ["*"],
});

export const badgeRecipe = defineRecipe({
  className: "badge",
  base: {
    display: "inline-flex",
    alignItems: "center",
    gap: "1",
    borderRadius: "full",
    fontFamily: "system-ui, sans-serif",
    fontSize: "xs",
    fontWeight: "600",
    lineHeight: "1",
    px: "2",
    py: "1",
  },
  variants: {
    tone: {
      neutral: { bg: "neutral.600", color: "fg.onAccent" },
      accent: { bg: "accent.default", color: "fg.onAccent" },
      success: { bg: "success", color: "fg.onAccent" },
      warning: { bg: "warning", color: "fg.onAccent" },
      danger: { bg: "danger", color: "fg.onAccent" },
    },
  },
  defaultVariants: {
    tone: "neutral",
  },
  staticCss: ["*"],
});

export const stackRecipe = defineRecipe({
  className: "stack",
  base: {
    display: "flex",
  },
  variants: {
    direction: {
      vertical: { flexDirection: "column" },
      horizontal: { flexDirection: "row" },
    },
    gap: {
      none: { gap: "0" },
      sm: { gap: "2" },
      md: { gap: "4" },
      lg: { gap: "6" },
      xl: { gap: "8" },
    },
    align: {
      start: { alignItems: "flex-start" },
      center: { alignItems: "center" },
      end: { alignItems: "flex-end" },
      stretch: { alignItems: "stretch" },
    },
    justify: {
      start: { justifyContent: "flex-start" },
      center: { justifyContent: "center" },
      end: { justifyContent: "flex-end" },
      between: { justifyContent: "space-between" },
    },
    wrap: {
      wrap: { flexWrap: "wrap" },
      nowrap: { flexWrap: "nowrap" },
    },
  },
  defaultVariants: {
    direction: "vertical",
    gap: "md",
    align: "stretch",
    justify: "start",
    wrap: "nowrap",
  },
  staticCss: ["*"],
});

export const gridRecipe = defineRecipe({
  className: "grid",
  base: {
    display: "grid",
  },
  variants: {
    columns: {
      1: { gridTemplateColumns: "repeat(1, minmax(0, 1fr))" },
      2: {
        gridTemplateColumns: {
          base: "repeat(1, minmax(0, 1fr))",
          md: "repeat(2, minmax(0, 1fr))",
        },
      },
      3: {
        gridTemplateColumns: {
          base: "repeat(1, minmax(0, 1fr))",
          md: "repeat(2, minmax(0, 1fr))",
          lg: "repeat(3, minmax(0, 1fr))",
        },
      },
      4: {
        gridTemplateColumns: {
          base: "repeat(1, minmax(0, 1fr))",
          sm: "repeat(2, minmax(0, 1fr))",
          md: "repeat(3, minmax(0, 1fr))",
          lg: "repeat(4, minmax(0, 1fr))",
        },
      },
    },
    gap: {
      none: { gap: "0" },
      sm: { gap: "2" },
      md: { gap: "4" },
      lg: { gap: "6" },
      xl: { gap: "8" },
    },
  },
  defaultVariants: {
    columns: 3,
    gap: "md",
  },
  staticCss: ["*"],
});

export const separatorRecipe = defineRecipe({
  className: "separator",
  base: {
    borderStyle: "solid",
    borderWidth: "0",
    borderColor: "border.default",
    flexShrink: "0",
  },
  variants: {
    orientation: {
      horizontal: { borderTopWidth: "1px", width: "100%" },
      vertical: { borderLeftWidth: "1px", height: "100%", alignSelf: "stretch" },
    },
  },
  defaultVariants: {
    orientation: "horizontal",
  },
  staticCss: ["*"],
});

export const spinnerRecipe = defineRecipe({
  className: "spinner",
  base: {
    animation: "spin",
    borderColor: "transparent",
    borderBottomColor: "fg.default",
    borderStyle: "solid",
    borderTopColor: "fg.default",
    borderRadius: "full",
  },
  variants: {
    size: {
      sm: { width: "4", height: "4", borderWidth: "2px" },
      md: { width: "6", height: "6", borderWidth: "2px" },
      lg: { width: "8", height: "8", borderWidth: "3px" },
    },
  },
  defaultVariants: {
    size: "md",
  },
  staticCss: ["*"],
});

export const buttonRecipe = defineRecipe({
  className: "button",
  base: {
    alignItems: "center",
    borderColor: "border.interactive",
    borderRadius: "lg",
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    cursor: "pointer",
    display: "inline-flex",
    flexBasis: "max-content",
    fontFamily: "system-ui, sans-serif",
    fontWeight: "500",
    gap: "2",
    justifyContent: "center",
    maxWidth: "100%",
    minWidth: "0",
    overflowWrap: "anywhere",
    textAlign: "center",
    transitionDuration: "slow",
    transitionProperty: "background-color, border-color, box-shadow, color, transform",
    transitionTimingFunction: "standard",
    whiteSpace: "normal",
    _disabled: {
      cursor: "not-allowed",
      opacity: "0.5",
    },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.default",
      outlineOffset: "2px",
    },
    _active: {
      transform: "translateY(0)",
    },
  },
  variants: {
    variant: {
      outline: {
        bg: "transparent",
        color: "fg.default",
        _hover: {
          backgroundColor: "surface.subtle",
          borderColor: "fg.muted",
          boxShadow: "xl",
          transform: "translateY(-1px)",
        },
      },
      solid: {
        bg: "accent.default",
        borderColor: "accent.default",
        color: "fg.onAccent",
        _hover: {
          bg: "accent.hover",
          borderColor: "accent.hover",
          boxShadow: "lg",
          transform: "translateY(-1px)",
        },
      },
      ghost: {
        bg: "transparent",
        borderColor: "transparent",
        color: "fg.default",
        _hover: { bg: "surface.subtle", boxShadow: "lg", transform: "translateY(-1px)" },
      },
      danger: {
        bg: "danger",
        borderColor: "danger",
        color: "fg.onAccent",
        _hover: { boxShadow: "lg", transform: "translateY(-1px)" },
      },
    },
    size: {
      sm: { fontSize: "sm", minHeight: "9", px: "3", py: "2" },
      md: {
        fontSize: { base: "sm", lg: "md" },
        minHeight: { base: "10", lg: "12" },
        px: { base: "3", lg: "4" },
        py: { base: "2", lg: "3" },
      },
      lg: { fontSize: "lg", minHeight: "12", px: "5", py: "3" },
    },
    fullWidth: {
      true: { width: "100%" },
    },
  },
  defaultVariants: {
    variant: "outline",
    size: "md",
    fullWidth: false,
  },
  staticCss: ["*"],
});

export const cardRecipe = defineSlotRecipe({
  className: "card",
  slots: ["root", "header", "title", "content", "footer"],
  base: {
    root: {
      backgroundColor: "surface.default",
      backdropFilter: "blur(12px)",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "2px",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
      transitionDuration: "slow",
      transitionProperty: "background-color, border-color, box-shadow, transform",
      transitionTimingFunction: "standard",
      _hover: {
        boxShadow: "xl",
        transform: "translateY(-2px)",
      },
    },
    header: {
      display: "flex",
      flexDirection: "column",
      gap: "1",
      px: "6",
      pt: "6",
    },
    title: {
      alignItems: "center",
      display: "flex",
      gap: "1",
      fontSize: { base: "lg", md: "xl", lg: "2xl" },
      fontWeight: "700",
      lineHeight: "1.5",
    },
    content: {
      flex: "1",
      px: "6",
      py: "6",
    },
    footer: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      marginTop: "auto",
      px: "6",
      pb: "6",
      pt: "2",
    },
  },
  variants: {
    variant: {
      outline: { root: {} },
      elevated: { root: { boxShadow: "md" } },
      subtle: { root: { backgroundColor: "surface.raised", borderColor: "transparent" } },
    },
  },
  defaultVariants: {
    variant: "outline",
  },
  staticCss: ["*"],
});

export const fieldRecipe = defineSlotRecipe({
  className: "field",
  slots: ["root", "label", "description", "error", "control"],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
    },
    label: {
      color: "fg.default",
      fontSize: "sm",
      fontWeight: "700",
      marginInlineStart: "2",
    },
    description: {
      color: "fg.muted",
      fontSize: "sm",
    },
    error: {
      color: "danger",
      fontSize: "sm",
      fontWeight: "600",
    },
    control: {
      width: "100%",
    },
  },
  variants: {
    invalid: {
      true: {
        label: { color: "danger" },
      },
    },
  },
  defaultVariants: {
    invalid: false,
  },
  staticCss: ["*"],
});

export const inputRecipe = defineRecipe({
  className: "input",
  base: {
    backgroundColor: "transparent",
    borderColor: "border.default",
    borderRadius: "lg",
    borderStyle: "solid",
    borderWidth: "2px",
    boxSizing: "border-box",
    color: "fg.default",
    fontFamily: "system-ui, sans-serif",
    outline: "none",
    transitionDuration: "slow",
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: "standard",
    width: "100%",
    _placeholder: { color: "fg.muted" },
    _disabled: { cursor: "not-allowed", opacity: "0.55" },
    _hover: {
      borderColor: "border.strong",
      boxShadow: "sm",
    },
    _focusVisible: {
      borderColor: "accent.default",
      outline: "2px solid",
      outlineColor: "accent.default",
      outlineOffset: "2px",
    },
    _invalid: {
      borderColor: "danger",
    },
  },
  variants: {
    size: {
      sm: { fontSize: "sm", minHeight: "9", px: "2", py: "2" },
      md: {
        fontSize: { base: "sm", lg: "md" },
        minHeight: { base: "10", lg: "12" },
        px: { base: "2", lg: "4" },
        py: { base: "2", lg: "3" },
      },
      lg: { fontSize: "lg", minHeight: "12", px: "4", py: "3" },
    },
  },
  defaultVariants: {
    size: "md",
  },
  staticCss: ["*"],
});

export const textareaRecipe = defineRecipe({
  className: "textarea",
  base: {
    backgroundColor: "transparent",
    borderColor: "border.default",
    borderRadius: "lg",
    borderStyle: "solid",
    borderWidth: "2px",
    boxSizing: "border-box",
    color: "fg.default",
    fontFamily: "system-ui, sans-serif",
    minHeight: "24",
    outline: "none",
    px: "3",
    py: "2",
    resize: "vertical",
    transitionDuration: "slow",
    transitionProperty: "border-color, box-shadow",
    transitionTimingFunction: "standard",
    width: "100%",
    _placeholder: { color: "fg.muted" },
    _disabled: { cursor: "not-allowed", opacity: "0.55" },
    _hover: {
      borderColor: "border.strong",
      boxShadow: "sm",
    },
    _focusVisible: {
      borderColor: "accent.default",
      outline: "2px solid",
      outlineColor: "accent.default",
      outlineOffset: "2px",
    },
    _invalid: {
      borderColor: "danger",
    },
  },
  variants: {
    size: {
      sm: { fontSize: "sm" },
      md: { fontSize: "md" },
      lg: { fontSize: "lg" },
    },
  },
  defaultVariants: {
    size: "md",
  },
  staticCss: ["*"],
});

export const controlRecipe = defineRecipe({
  className: "control",
  base: {
    accentColor: "accent.default",
    cursor: "pointer",
    height: "4",
    width: "4",
    _disabled: { cursor: "not-allowed", opacity: "0.55" },
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.default",
      outlineOffset: "2px",
    },
  },
  variants: {
    kind: {
      checkbox: { borderRadius: "sm" },
      radio: { borderRadius: "full" },
    },
  },
  staticCss: ["*"],
});

export const switchRecipe = defineSlotRecipe({
  className: "toggleSwitch",
  slots: ["root", "thumb"],
  base: {
    root: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "surface.subtle",
      border: "0",
      borderRadius: "full",
      boxSizing: "border-box",
      cursor: "pointer",
      display: "inline-flex",
      flex: "0 0 auto",
      fontFamily: "inherit",
      height: "6",
      justifyContent: "flex-start",
      p: "1",
      transitionDuration: "fast",
      transitionProperty: "background-color, box-shadow, transform",
      width: "11",
      _hover: { backgroundColor: "border.strong" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    thumb: {
      backgroundColor: "surface.raised",
      borderRadius: "full",
      boxShadow: "sm",
      height: "4",
      transitionDuration: "fast",
      transitionProperty: "transform",
      width: "4",
    },
  },
  variants: {
    checked: {
      true: {
        root: { backgroundColor: "accent.default", _hover: { backgroundColor: "accent.hover" } },
        thumb: { transform: "translateX(1.25rem)" },
      },
    },
  },
  defaultVariants: {
    checked: false,
  },
  staticCss: ["*"],
});

export const tabsRecipe = defineSlotRecipe({
  className: "tabs",
  slots: ["root", "list", "tab", "panel"],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      minWidth: "0",
      width: "100%",
    },
    list: {
      alignItems: "center",
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      display: "flex",
      gap: "1",
      maxWidth: "100%",
      overflowX: "auto",
      position: "relative",
      width: "100%",
      "&[data-orientation=vertical]": {
        alignItems: "stretch",
        borderBottomWidth: "0",
        borderRightColor: "border.default",
        borderRightStyle: "solid",
        borderRightWidth: "1px",
        flexDirection: "column",
        overflowX: "visible",
      },
    },
    tab: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "md",
      fontWeight: "600",
      gap: "2",
      justifyContent: "center",
      px: "3",
      py: "2",
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      whiteSpace: "nowrap",
      "&::after": {
        backgroundColor: "transparent",
        borderRadius: "full",
        bottom: "0",
        content: '""',
        height: "1",
        left: "2",
        position: "absolute",
        right: "2",
        transitionDuration: "normal",
        transitionProperty: "background-color",
        transitionTimingFunction: "standard",
      },
      "&[data-active]": {
        color: "fg.default",
        "&::after": { backgroundColor: "accent.default" },
      },
      "&[data-orientation=vertical]": {
        justifyContent: "flex-start",
        "&::after": {
          bottom: "2",
          height: "auto",
          left: "auto",
          right: "0",
          top: "2",
          width: "1",
        },
      },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { color: "fg.default" },
    },
    panel: {
      color: "fg.default",
      minWidth: "0",
      outline: "none",
      pt: "2",
      transitionDuration: "fast",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      "&[data-starting-style]": { opacity: "0", transform: "translateY(-0.25rem)" },
      "&[data-ending-style]": { opacity: "0", transform: "translateY(-0.25rem)" },
    },
  },
  variants: {
    variant: {
      underline: {},
      pills: {
        list: { borderBottomWidth: "0", gap: "2" },
        tab: {
          borderRadius: "full",
          "&::after": { display: "none" },
          "&[data-active]": {
            backgroundColor: "accent.default",
            color: "fg.onAccent",
          },
          _hover: { backgroundColor: "surface.subtle" },
        },
      },
    },
  },
  defaultVariants: {
    variant: "underline",
  },
  staticCss: ["*"],
});

export const accordionRecipe = defineSlotRecipe({
  className: "accordion",
  slots: ["root", "item", "header", "trigger", "panel", "indicator"],
  base: {
    root: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      overflow: "hidden",
    },
    item: {
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      "&:last-child": { borderBottomWidth: "0" },
    },
    header: { margin: "0" },
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "md",
      fontWeight: "700",
      gap: "3",
      justifyContent: "flex-start",
      px: "4",
      py: "3",
      textAlign: "left",
      transitionDuration: "normal",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      width: "100%",
      "&[data-panel-open] [data-slot=accordion-indicator]": {
        color: "accent.default",
        transform: "rotate(90deg)",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle", color: "accent.hover" },
    },
    panel: {
      color: "fg.default",
      height: "var(--accordion-panel-height)",
      overflow: "hidden",
      pb: "4",
      px: "4",
      transitionDuration: "normal",
      transitionProperty: "height, opacity",
      transitionTimingFunction: "standard",
      "&[data-starting-style]": { height: "0", opacity: "0" },
      "&[data-ending-style]": { height: "0", opacity: "0" },
    },
    indicator: {
      color: "fg.muted",
      flexShrink: "0",
      fontSize: "lg",
      lineHeight: "1",
      transitionDuration: "normal",
      transitionProperty: "color, transform",
      transitionTimingFunction: "standard",
    },
  },
  staticCss: ["*"],
});

export const collapsibleRecipe = defineSlotRecipe({
  className: "collapsible",
  slots: ["root", "trigger", "panel", "indicator"],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
    },
    trigger: {
      alignItems: "center",
      alignSelf: "flex-start",
      backgroundColor: "transparent",
      border: "0",
      color: "accent.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "md",
      fontWeight: "700",
      gap: "3",
      p: "0",
      transitionDuration: "normal",
      transitionProperty: "color",
      transitionTimingFunction: "standard",
      "&[data-panel-open] [data-slot=collapsible-indicator]": {
        transform: "rotate(90deg)",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "4px",
      },
      _hover: { color: "accent.hover" },
    },
    panel: {
      color: "fg.default",
      height: "var(--collapsible-panel-height)",
      overflow: "hidden",
      pt: "2",
      transitionDuration: "normal",
      transitionProperty: "height, opacity",
      transitionTimingFunction: "standard",
      "&[data-starting-style]": { height: "0", opacity: "0" },
      "&[data-ending-style]": { height: "0", opacity: "0" },
    },
    indicator: {
      color: "currentColor",
      flexShrink: "0",
      fontSize: "lg",
      lineHeight: "1",
      transitionDuration: "normal",
      transitionProperty: "transform",
      transitionTimingFunction: "standard",
    },
  },
  staticCss: ["*"],
});

export const dialogRecipe = defineSlotRecipe({
  className: "dialog",
  slots: [
    "trigger",
    "backdrop",
    "viewport",
    "popup",
    "header",
    "title",
    "description",
    "body",
    "footer",
    "close",
    "action",
  ],
  base: {
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.interactive",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: { base: "sm", lg: "md" },
      fontWeight: "500",
      gap: "2",
      justifyContent: "center",
      minHeight: { base: "10", lg: "12" },
      px: { base: "3", lg: "4" },
      py: "2",
      transitionDuration: "slow",
      transitionProperty: "background-color, border-color, box-shadow, color, transform",
      transitionTimingFunction: "standard",
      _active: { transform: "translateY(0)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: {
        backgroundColor: "surface.subtle",
        borderColor: "fg.muted",
        boxShadow: "xl",
        transform: "translateY(-1px)",
      },
    },
    backdrop: {
      backdropBlur: "xs",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      inset: "0",
      minHeight: "100dvh",
      position: "fixed",
      transitionDuration: "fast",
      transitionProperty: "opacity",
      transitionTimingFunction: "standard",
      zIndex: "50",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
    },
    viewport: {
      alignItems: "center",
      display: "flex",
      inset: "0",
      justifyContent: "center",
      overflow: "hidden",
      p: { base: "4", md: "6" },
      position: "fixed",
      zIndex: "50",
    },
    popup: {
      backgroundColor: "surface.canvas",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      height: "calc(100dvh - 2rem)",
      maxHeight: "calc(100dvh - 2rem)",
      maxWidth: "100%",
      minHeight: "0",
      overflow: "hidden",
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: { base: "11/12", md: "8/12", lg: "6/12" },
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.98)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.98)" },
    },
    header: {
      alignItems: "center",
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      display: "flex",
      flexShrink: "0",
      gap: "4",
      justifyContent: "space-between",
      p: { base: "4", md: "6" },
    },
    title: {
      color: "fg.default",
      fontFamily: "system-ui, sans-serif",
      fontSize: { base: "2xl", md: "3xl", lg: "4xl" },
      fontWeight: "700",
      lineHeight: "1.25",
      margin: "0",
    },
    description: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "md",
      lineHeight: "1.5",
      margin: "0",
    },
    body: {
      color: "fg.default",
      flex: "1",
      minHeight: "0",
      overflowY: "auto",
      p: { base: "4", md: "6" },
    },
    footer: {
      alignItems: "center",
      borderTopColor: "border.default",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      display: "flex",
      flexShrink: "0",
      flexWrap: "wrap",
      gap: "2",
      justifyContent: "flex-end",
      p: { base: "4", md: "6" },
      "& > *": { maxWidth: "100%", minWidth: "0" },
    },
    close: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xl",
      height: "8",
      justifyContent: "center",
      transitionDuration: "slow",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      width: "8",
      _active: { transform: "scale(0.95)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "danger", color: "fg.onAccent" },
    },
    action: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.interactive",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      flex: "0 0 auto",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "500",
      justifyContent: "center",
      lineHeight: "1.25",
      maxWidth: "100%",
      minHeight: "9",
      minWidth: "0",
      px: "3",
      py: "2",
      transitionDuration: "slow",
      transitionProperty: "background-color, border-color, box-shadow, color, transform",
      transitionTimingFunction: "standard",
      textAlign: "center",
      whiteSpace: "normal",
      overflowWrap: "anywhere",
      _active: { transform: "translateY(0)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: {
        backgroundColor: "surface.subtle",
        borderColor: "fg.muted",
        boxShadow: "xl",
        transform: "translateY(-1px)",
      },
    },
  },
  variants: {
    size: {
      sm: {
        popup: {
          height: "auto",
          maxWidth: "28rem",
          width: "100%",
        },
      },
      md: {},
      lg: {
        popup: {
          width: { base: "11/12", lg: "10/12" },
        },
      },
    },
  },
  defaultVariants: {
    size: "md",
  },
  staticCss: ["*"],
});

/**
 * The select has the same quiet field treatment as the original input: a
 * transparent zinc control, a clear focus ring, and a blurred dropdown with
 * rounded option rows. Base UI supplies its keyboard, form, and listbox
 * semantics; this recipe only owns the visual language.
 */
export const selectRecipe = defineSlotRecipe({
  className: "select",
  slots: [
    "label",
    "trigger",
    "value",
    "icon",
    "positioner",
    "popup",
    "list",
    "item",
    "itemText",
    "itemIndicator",
    "group",
    "groupLabel",
    "separator",
    "clear",
    "empty",
    "loading",
    "status",
  ],
  base: {
    label: {
      color: "fg.default",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "700",
      marginInlineStart: "2",
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "2px",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "system-ui, sans-serif",
      gap: "2",
      justifyContent: "space-between",
      maxWidth: "100%",
      minWidth: "0",
      outline: "none",
      textAlign: "left",
      transitionDuration: "slow",
      transitionProperty: "border-color, box-shadow, color",
      transitionTimingFunction: "standard",
      width: "100%",
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
      _focusVisible: {
        borderColor: "accent.default",
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: {
        borderColor: "border.strong",
        boxShadow: "sm",
      },
      "&[aria-invalid=true], &[data-invalid]": { borderColor: "danger" },
      "&[data-popup-open]": { borderColor: "accent.default", boxShadow: "sm" },
    },
    value: {
      flex: "1",
      minWidth: "0",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      "&[data-placeholder]": { color: "fg.muted" },
    },
    icon: {
      color: "fg.muted",
      flexShrink: "0",
      fontSize: "lg",
      lineHeight: "1",
      transitionDuration: "normal",
      transitionProperty: "color, transform",
      transitionTimingFunction: "standard",
      "&[data-popup-open]": { color: "accent.default", transform: "rotate(180deg)" },
    },
    positioner: {
      outline: "none",
      zIndex: "50",
    },
    popup: {
      backdropBlur: "md",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      boxSizing: "border-box",
      color: "fg.default",
      maxHeight: "var(--available-height)",
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "0",
      overflow: "hidden",
      p: "2",
      transformOrigin: "var(--transform-origin)",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: "min(var(--anchor-width, 100%), calc(100vw - 2rem))",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.96)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.96)" },
    },
    list: {
      display: "flex",
      flexDirection: "column",
      gap: "1",
      maxHeight: "var(--available-height)",
      overflowY: "auto",
      overscrollBehavior: "contain",
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "lg",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      gap: "2",
      justifyContent: "flex-start",
      minHeight: "9",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      px: "3",
      py: "2",
      textAlign: "left",
      transitionDuration: "normal",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      width: "100%",
      "&[data-highlighted]": { backgroundColor: "surface.subtle", color: "fg.default" },
      "&[data-selected]": { backgroundColor: "accent.default", color: "fg.onAccent" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    itemText: {
      flex: "1",
      minWidth: "0",
      overflow: "hidden",
      textOverflow: "ellipsis",
      overflowWrap: "anywhere",
      whiteSpace: "normal",
    },
    itemIndicator: {
      color: "currentColor",
      flexShrink: "0",
      fontSize: "sm",
      lineHeight: "1",
      marginInlineStart: "auto",
      transitionDuration: "fast",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.8)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.8)" },
    },
    group: {
      display: "flex",
      flexDirection: "column",
      gap: "1",
      maxWidth: "100%",
      minWidth: "0",
    },
    groupLabel: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xs",
      fontWeight: "700",
      letterSpacing: "wide",
      pb: "1",
      pt: "2",
      px: "3",
      textTransform: "uppercase",
    },
    separator: {
      borderColor: "border.default",
      borderStyle: "solid",
      borderWidth: "0",
      flexShrink: "0",
      my: "2",
      "&[data-orientation=horizontal]": { borderTopWidth: "1px", width: "100%" },
      "&[data-orientation=vertical]": { alignSelf: "stretch", borderLeftWidth: "1px" },
    },
    clear: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "sm",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "lg",
      justifyContent: "center",
      minHeight: "6",
      minWidth: "6",
      _focusVisible: { outline: "2px solid", outlineColor: "accent.default", outlineOffset: "1px" },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    empty: { color: "fg.muted", fontSize: "sm", px: "3", py: "2" },
    loading: { color: "fg.muted", fontSize: "sm", px: "3", py: "2" },
    status: { color: "fg.muted", fontSize: "sm" },
  },
  variants: {
    size: {
      sm: {
        trigger: { fontSize: "sm", minHeight: "9", px: "2", py: "2" },
      },
      md: {
        trigger: {
          fontSize: { base: "sm", lg: "md" },
          minHeight: { base: "10", lg: "12" },
          px: { base: "2", lg: "4" },
          py: { base: "2", lg: "3" },
        },
      },
      lg: {
        trigger: { fontSize: "lg", minHeight: "12", px: "4", py: "3" },
      },
    },
  },
  defaultVariants: {
    size: "md",
  },
  staticCss: ["*"],
});

export const menuRecipe = defineSlotRecipe({
  className: "menu",
  slots: ["trigger", "positioner", "popup", "item", "separator", "group", "groupLabel"],
  base: {
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "lg",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      gap: "1",
      justifyContent: "center",
      maxWidth: "100%",
      minWidth: "0",
      overflow: "hidden",
      p: "2",
      transitionDuration: "slow",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      "&[data-popup-open]": { backgroundColor: "surface.subtle" },
    },
    positioner: {
      outline: "none",
      zIndex: "50",
    },
    popup: {
      backgroundColor: "surface.overlay",
      backdropFilter: "blur(12px)",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      boxSizing: "border-box",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      gap: "1",
      maxHeight: "var(--available-height)",
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "min(13rem, calc(100vw - 2rem))",
      overflowX: "hidden",
      overflowY: "auto",
      p: "6",
      transformOrigin: "var(--transform-origin)",
      transitionDuration: "slow",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.96)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.96)" },
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "xl",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      gap: "2",
      justifyContent: "flex-start",
      p: "2",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      textAlign: "left",
      textDecoration: "none",
      transitionDuration: "slow",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      overflowWrap: "anywhere",
      whiteSpace: "normal",
      width: "100%",
      "&[data-highlighted]": { backgroundColor: "surface.subtle", color: "fg.default" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    separator: {
      borderColor: "border.default",
      borderStyle: "solid",
      borderWidth: "0",
      flexShrink: "0",
      my: "2",
      "&[data-orientation=horizontal]": { borderTopWidth: "1px", width: "100%" },
      "&[data-orientation=vertical]": { alignSelf: "stretch", borderLeftWidth: "1px" },
    },
    group: {
      display: "flex",
      flexDirection: "column",
      gap: "1",
      maxWidth: "100%",
      minWidth: "0",
    },
    groupLabel: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xs",
      fontWeight: "700",
      letterSpacing: "wide",
      pb: "1",
      pt: "2",
      px: "2",
      textTransform: "uppercase",
    },
  },
  staticCss: ["*"],
});

/**
 * The toast keeps the original Jaci notification's bottom-centred placement,
 * zinc surface, rounded corners, and coloured status treatments. The stacking
 * variables are supplied by Base UI's toast store.
 */
export const toastRecipe = defineSlotRecipe({
  className: "toast",
  slots: ["viewport", "root", "content", "text", "title", "description", "close", "action"],
  base: {
    viewport: {
      bottom: { base: "4", md: "6" },
      left: "50%",
      maxWidth: "28rem",
      minHeight: "0",
      pointerEvents: "none",
      position: "fixed",
      transform: "translateX(-50%)",
      width: "calc(100vw - 2rem)",
      zIndex: "50",
    },
    root: {
      "--jaci-toast-gap": "1rem",
      "--jaci-toast-height": "var(--toast-frontmost-height, var(--toast-height))",
      "--jaci-toast-offset-y":
        "calc((var(--toast-offset-y) * -1) + (var(--toast-index) * var(--jaci-toast-gap) * -1) + var(--toast-swipe-movement-y))",
      "--jaci-toast-peek": "0.75rem",
      "--jaci-toast-scale": "calc(max(0, 1 - (var(--toast-index) * 0.08)))",
      "--jaci-toast-shrink": "calc(1 - var(--jaci-toast-scale))",
      backdropBlur: "md",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      bottom: "0",
      boxShadow: "lg",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "default",
      height: "var(--jaci-toast-height)",
      left: "0",
      margin: "0",
      overflow: "hidden",
      pointerEvents: "auto",
      position: "absolute",
      right: "0",
      transform:
        "translateX(var(--toast-swipe-movement-x)) translateY(calc(var(--toast-swipe-movement-y) - (var(--toast-index) * var(--jaci-toast-peek)) - (var(--jaci-toast-shrink) * var(--jaci-toast-height)))) scale(var(--jaci-toast-scale))",
      transformOrigin: "bottom center",
      transitionDuration: "slow",
      transitionProperty: "height, opacity, transform",
      transitionTimingFunction: "standard",
      userSelect: "none",
      width: "100%",
      zIndex: "calc(1000 - var(--toast-index))",
      "&::after": {
        content: '""',
        height: "calc(var(--jaci-toast-gap) + 1px)",
        left: "0",
        position: "absolute",
        top: "100%",
        width: "100%",
      },
      "&[data-expanded]": {
        height: "var(--toast-height)",
        transform:
          "translateX(var(--toast-swipe-movement-x)) translateY(var(--jaci-toast-offset-y))",
      },
      "&[data-limited]": { opacity: "0", pointerEvents: "none" },
      "&[data-starting-style]": { opacity: "0", transform: "translateY(150%)" },
      "&[data-ending-style]": { opacity: "0", transform: "translateY(150%)" },
      "&[data-ending-style][data-swipe-direction=down]": {
        transform: "translateY(calc(var(--toast-swipe-movement-y) + 150%))",
      },
      "&[data-ending-style][data-swipe-direction=up]": {
        transform: "translateY(calc(var(--toast-swipe-movement-y) - 150%))",
      },
      "&[data-ending-style][data-swipe-direction=left]": {
        transform:
          "translateX(calc(var(--toast-swipe-movement-x) - 150%)) translateY(var(--jaci-toast-offset-y))",
      },
      "&[data-ending-style][data-swipe-direction=right]": {
        transform:
          "translateX(calc(var(--toast-swipe-movement-x) + 150%)) translateY(var(--jaci-toast-offset-y))",
      },
    },
    content: {
      alignItems: "center",
      display: "flex",
      gap: "4",
      height: "100%",
      overflow: "hidden",
      p: "4",
      transitionDuration: "normal",
      transitionProperty: "opacity",
      transitionTimingFunction: "standard",
      "&[data-behind]": { opacity: "0" },
      "&[data-expanded]": { opacity: "1" },
    },
    text: {
      display: "flex",
      flex: "1",
      flexDirection: "column",
      gap: "1",
      minWidth: "0",
    },
    title: {
      color: "inherit",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "700",
      lineHeight: "1.5",
      margin: "0",
    },
    description: {
      color: "inherit",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      lineHeight: "1.5",
      margin: "0",
    },
    close: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "inherit",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xl",
      height: "8",
      justifyContent: "center",
      transitionDuration: "slow",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: "8",
      _active: { transform: "scale(0.95)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "currentColor",
        outlineOffset: "2px",
      },
      _hover: { opacity: "0.5" },
    },
    action: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "currentColor",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "inherit",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      justifyContent: "center",
      maxWidth: "100%",
      minWidth: "0",
      overflow: "hidden",
      overflowWrap: "anywhere",
      px: "3",
      py: "2",
      whiteSpace: "normal",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      _active: { transform: "scale(0.98)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "currentColor",
        outlineOffset: "2px",
      },
      _hover: { opacity: "0.72" },
    },
  },
  variants: {
    tone: {
      neutral: {},
      info: {
        root: {
          backgroundColor: "accent.default",
          borderColor: "accent.hover",
          color: "fg.onAccent",
        },
      },
      success: {
        root: { backgroundColor: "success", borderColor: "green.700", color: "fg.onAccent" },
      },
      warning: {
        root: { backgroundColor: "warning", borderColor: "amber.700", color: "fg.onAccent" },
      },
      danger: {
        root: { backgroundColor: "danger", borderColor: "red.600", color: "fg.onAccent" },
      },
    },
  },
  defaultVariants: {
    tone: "neutral",
  },
  staticCss: ["*"],
});

/**
 * The sidebar follows the original Jaci navigation treatment: zinc borders,
 * a generous expanded width, compact icon rail, and a floating round toggle.
 * Labels shrink visually rather than being removed so icon-only navigation
 * stays understandable to assistive technology while collapsed.
 */
export const sidebarRecipe = defineSlotRecipe({
  className: "sidebar",
  slots: [
    "root",
    "popup",
    "backdrop",
    "viewport",
    "toggle",
    "header",
    "content",
    "footer",
    "item",
    "label",
  ],
  base: {
    root: {
      backgroundColor: "surface.canvas",
      borderRightColor: "border.default",
      borderRightStyle: "solid",
      borderRightWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      flexShrink: "0",
      height: "100%",
      minWidth: "0",
      overflow: "visible",
      position: "relative",
      transitionDuration: "slow",
      transitionProperty: "background-color, border-color, width",
      transitionTimingFunction: "standard",
    },
    popup: {
      backgroundColor: "transparent",
      border: "0",
      boxSizing: "border-box",
      height: "100dvh",
      maxWidth: "min(22rem, calc(100vw - 1rem))",
      minWidth: "0",
      outline: "none",
      overflow: "visible",
      padding: "0",
    },
    backdrop: {
      backdropBlur: "xs",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      inset: "0",
      position: "fixed",
      zIndex: "50",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
    },
    viewport: {
      alignItems: "flex-start",
      display: "flex",
      inset: "0",
      overflow: "hidden",
      position: "fixed",
      zIndex: "50",
    },
    toggle: {
      alignItems: "center",
      backgroundColor: "surface.canvas",
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "md",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xl",
      height: "8",
      justifyContent: "center",
      p: "2",
      position: "absolute",
      right: "-4",
      top: "4",
      transitionDuration: "fast",
      transitionProperty: "background-color, border-color, box-shadow, color, transform",
      transitionTimingFunction: "standard",
      width: "8",
      zIndex: "10",
      _active: { transform: "scale(0.96)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: {
        backgroundColor: "surface.raised",
        borderColor: "border.strong",
        boxShadow: "lg",
        transform: "scale(1.1)",
      },
    },
    header: {
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      display: "flex",
      flexDirection: "column",
      gap: "2",
      minWidth: "0",
      p: "3",
      transitionDuration: "slow",
      transitionProperty: "padding",
      transitionTimingFunction: "standard",
    },
    content: {
      display: "flex",
      flex: "1",
      flexDirection: "column",
      gap: "2",
      minHeight: "0",
      minWidth: "0",
      overflowX: "hidden",
      overflowY: "auto",
      p: "3",
      transitionDuration: "slow",
      transitionProperty: "padding",
      transitionTimingFunction: "standard",
    },
    footer: {
      borderTopColor: "border.default",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      display: "flex",
      flexDirection: "column",
      gap: "2",
      minWidth: "0",
      p: "3",
      transitionDuration: "slow",
      transitionProperty: "padding",
      transitionTimingFunction: "standard",
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderRadius: "lg",
      boxSizing: "border-box",
      color: "fg.muted",
      display: "flex",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      gap: "3",
      minHeight: "10",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      px: "3",
      py: "2",
      textAlign: "left",
      textDecoration: "none",
      transitionDuration: "normal",
      transitionProperty: "background-color, color, padding",
      transitionTimingFunction: "standard",
      whiteSpace: "nowrap",
      width: "100%",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _hover: { backgroundColor: "surface.subtle", color: "fg.default" },
    },
    label: {
      display: "block",
      flex: "1",
      minWidth: "0",
      overflow: "hidden",
      textOverflow: "ellipsis",
      transitionDuration: "slow",
      transitionProperty: "max-width, opacity, transform",
      transitionTimingFunction: "standard",
      whiteSpace: "nowrap",
    },
  },
  variants: {
    active: {
      true: {
        item: {
          backgroundColor: "surface.subtle",
          color: "fg.default",
        },
      },
      false: {},
    },
    open: {
      true: {
        label: { maxWidth: "100%", opacity: "1", transform: "translateX(0)" },
        root: { width: { base: "48", md: "64" } },
      },
      false: {
        content: { alignItems: "center", px: "2" },
        footer: { alignItems: "center", px: "2" },
        header: { alignItems: "center", px: "2" },
        item: { justifyContent: "center", px: "2" },
        label: { maxWidth: "0", opacity: "0", transform: "translateX(-0.25rem)" },
        root: { width: { base: "18", md: "20" } },
      },
    },
  },
  defaultVariants: {
    active: false,
    open: true,
  },
  staticCss: ["*"],
});

/**
 * Fixed navigation. The drawer slots are intentionally separate from the
 * standard Dialog recipe because they form a left-aligned mobile navigation
 * surface instead of a modal card.
 */
export const navbarRecipe = defineSlotRecipe({
  className: "navbar",
  slots: [
    "bar",
    "start",
    "center",
    "end",
    "toggle",
    "drawerBackdrop",
    "drawerViewport",
    "drawer",
    "close",
    "item",
  ],
  base: {
    bar: {
      alignItems: "center",
      // Keep the blur as a concrete declaration in the distributed CSS. Some
      // framework CSS pipelines (notably Next.js) can drop Panda's composed
      // backdrop-filter custom-property declaration when it is imported as a
      // package stylesheet.
      backdropFilter: "blur(4px)",
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "1px",
      borderBottomWidth: "2px",
      boxShadow: "xl",
      boxSizing: "border-box",
      color: "fg.default",
      display: "grid",
      gap: "2",
      gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)",
      left: { base: "2", md: "4" },
      minHeight: { base: "16", md: "20" },
      p: { base: "3", md: "4" },
      position: "fixed",
      right: { base: "2", md: "4" },
      top: { base: "2", md: "4" },
      userSelect: "none",
      zIndex: "50",
    },
    start: {
      alignItems: "center",
      display: "flex",
      gap: "1",
      justifyContent: "flex-start",
      minWidth: "0",
    },
    center: {
      alignItems: "center",
      display: "flex",
      gap: "1",
      justifyContent: "center",
      minWidth: "0",
    },
    end: {
      alignItems: "center",
      display: "flex",
      gap: "1",
      justifyContent: "flex-end",
      minWidth: "0",
    },
    toggle: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "lg",
      color: "fg.default",
      cursor: "pointer",
      display: { base: "inline-flex", lg: "none" },
      fontFamily: "system-ui, sans-serif",
      fontSize: "xl",
      height: "10",
      justifyContent: "center",
      transitionDuration: "slow",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      width: "10",
      "&[data-popup-open]": { backgroundColor: "surface.subtle" },
      _active: { transform: "scale(0.95)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    drawerBackdrop: {
      backdropFilter: "blur(4px)",
      backgroundColor: "surface.overlay",
      inset: "0",
      position: "fixed",
      transitionDuration: "normal",
      transitionProperty: "opacity",
      transitionTimingFunction: "standard",
      zIndex: "40",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
    },
    drawerViewport: {
      alignItems: "stretch",
      display: "flex",
      inset: "0",
      justifyContent: "flex-start",
      overflow: "hidden",
      position: "fixed",
      zIndex: "40",
    },
    drawer: {
      backgroundColor: "surface.default",
      backdropFilter: "blur(8px)",
      borderColor: "border.default",
      borderRightStyle: "solid",
      borderRightWidth: "1px",
      boxSizing: "border-box",
      boxShadow: "xl",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      gap: "2",
      height: "100dvh",
      maxWidth: "min(28rem, calc(100vw - 1rem))",
      minWidth: "0",
      overflowY: "auto",
      p: "4",
      paddingTop: "24",
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: { base: "10/12", sm: "8/12", md: "5/12" },
      "& [data-slot=navbar-item]": {
        boxSizing: "border-box",
        borderRadius: "lg",
        fontSize: "md",
        maxWidth: "100%",
        minHeight: "12",
        minWidth: "0",
        overflow: "hidden",
        px: "4",
        py: "3",
        width: "100%",
      },
      "&[data-ending-style]": { opacity: "0", transform: "translateX(-1rem)" },
      "&[data-starting-style]": { opacity: "0", transform: "translateX(-1rem)" },
    },
    close: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xl",
      height: "10",
      justifyContent: "center",
      position: "absolute",
      right: "4",
      top: "6",
      transitionDuration: "slow",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      width: "10",
      _active: { transform: "scale(0.95)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "danger", color: "fg.onAccent" },
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderRadius: "lg",
      boxSizing: "border-box",
      color: "fg.default",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      gap: "2",
      justifyContent: "center",
      minHeight: "10",
      minWidth: "0",
      maxWidth: "100%",
      overflow: "hidden",
      px: "3",
      py: "2",
      textDecoration: "none",
      transitionDuration: "slow",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      overflowWrap: "anywhere",
      whiteSpace: "normal",
      "&[data-active]": { backgroundColor: "surface.subtle", color: "fg.default" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", transform: "translateY(-1px)" },
    },
  },
  variants: {
    active: {
      false: {},
      true: { item: { backgroundColor: "surface.subtle", color: "fg.default" } },
    },
  },
  defaultVariants: {
    active: false,
  },
  staticCss: ["*"],
});

/**
 * A compact, floating lower navigation that retains the original Bottombar's
 * blurred zinc surface, pronounced bottom border, and generous rounded shape.
 */
export const bottomNavigationRecipe = defineSlotRecipe({
  className: "bottomNavigation",
  slots: ["root", "item"],
  base: {
    root: {
      alignItems: "center",
      backdropBlur: "sm",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      borderColor: "border.default",
      borderRadius: { base: "full", lg: "2xl" },
      borderStyle: "solid",
      borderWidth: "1px",
      borderBottomWidth: "2px",
      boxShadow: "xl",
      boxSizing: "border-box",
      color: "fg.default",
      display: "flex",
      gap: { base: "2", md: "5" },
      left: "50%",
      maxWidth: "calc(100vw - 2rem)",
      p: "3",
      position: "fixed",
      transform: "translateX(-50%)",
      userSelect: "none",
      bottom: "2",
      zIndex: "40",
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderRadius: "lg",
      color: "fg.default",
      display: "inline-flex",
      flexDirection: "column",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xs",
      fontWeight: "600",
      gap: "1",
      justifyContent: "center",
      minHeight: "10",
      minWidth: "10",
      px: "2",
      py: "1",
      textAlign: "center",
      textDecoration: "none",
      transitionDuration: "slow",
      transitionProperty: "background-color, color, transform",
      transitionTimingFunction: "standard",
      "&[data-active]": { backgroundColor: "surface.subtle", color: "fg.default" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", transform: "translateY(-1px)" },
    },
  },
  variants: {
    active: {
      false: {},
      true: { item: { backgroundColor: "surface.subtle", color: "fg.default" } },
    },
  },
  defaultVariants: {
    active: false,
  },
  staticCss: ["*"],
});
