import { defineSlotRecipe } from "@pandacss/dev";

export const drawerRecipe = defineSlotRecipe({
  className: "drawer",
  slots: [
    "trigger",
    "backdrop",
    "viewport",
    "popup",
    "content",
    "header",
    "title",
    "description",
    "footer",
    "close",
    "action",
  ],
  base: {
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.interactive",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      gap: "2",
      justifyContent: "center",
      minHeight: "10",
      px: "3",
      py: "2",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", borderColor: "fg.muted" },
    },
    backdrop: {
      backdropBlur: "xs",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      inset: "0",
      position: "fixed",
      transitionDuration: "fast",
      transitionProperty: "opacity",
      transitionTimingFunction: "standard",
      zIndex: "50",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
    },
    viewport: {
      inset: "0",
      overflow: "hidden",
      pointerEvents: "none",
      position: "fixed",
      zIndex: "50",
    },
    popup: {
      backgroundColor: "surface.canvas",
      borderColor: "border.default",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      minHeight: "0",
      pointerEvents: "auto",
      position: "absolute",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: "100%",
      maxWidth: "100vw",
      overflow: "hidden",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-side=bottom]": {
        borderBottomWidth: "0",
        borderRadius: "2xl 2xl 0 0",
        bottom: "0",
        left: "0",
        maxHeight: "85dvh",
        right: "0",
      },
      "&[data-side=left]": {
        borderLeftWidth: "0",
        borderRadius: "0 2xl 2xl 0",
        bottom: "0",
        left: "0",
        maxWidth: "28rem",
        top: "0",
        width: "min(88vw, 28rem)",
      },
      "&[data-side=right]": {
        borderRadius: "2xl 0 0 2xl",
        bottom: "0",
        maxWidth: "28rem",
        right: "0",
        top: "0",
        width: "min(88vw, 28rem)",
      },
      "&[data-side=top]": {
        borderRadius: "0 0 2xl 2xl",
        left: "0",
        maxHeight: "85dvh",
        right: "0",
        top: "0",
      },
      "&[data-side=bottom][data-ending-style]": { transform: "translateY(100%)" },
      "&[data-side=bottom][data-starting-style]": { transform: "translateY(100%)" },
      "&[data-side=left][data-ending-style]": { transform: "translateX(-100%)" },
      "&[data-side=left][data-starting-style]": { transform: "translateX(-100%)" },
      "&[data-side=right][data-ending-style]": { transform: "translateX(100%)" },
      "&[data-side=right][data-starting-style]": { transform: "translateX(100%)" },
      "&[data-side=top][data-ending-style]": { transform: "translateY(-100%)" },
      "&[data-side=top][data-starting-style]": { transform: "translateY(-100%)" },
    },
    content: {
      color: "fg.default",
      flex: "1",
      minHeight: "0",
      overflowY: "auto",
      p: { base: "4", md: "6" },
    },
    header: {
      alignItems: "flex-start",
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      display: "flex",
      flexShrink: "0",
      gap: "3",
      justifyContent: "space-between",
      p: { base: "4", md: "6" },
    },
    title: {
      color: "fg.default",
      fontFamily: "system-ui, sans-serif",
      fontSize: { base: "xl", md: "2xl" },
      fontWeight: "700",
      lineHeight: "1.25",
      margin: "0",
    },
    description: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      lineHeight: "1.5",
      margin: "0",
    },
    footer: {
      alignItems: "center",
      borderTopColor: "border.default",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      display: "flex",
      flexShrink: "0",
      flexWrap: "wrap",
      gap: "2",
      justifyContent: "flex-end",
      p: { base: "4", md: "6" },
      "& > *": { maxWidth: "100%", minWidth: "0" },
    },
    close: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "xl",
      height: "8",
      justifyContent: "center",
      width: "8",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    action: {
      alignItems: "center",
      backgroundColor: "transparent",
      borderColor: "border.interactive",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      flex: "0 0 auto",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "500",
      justifyContent: "center",
      lineHeight: "1.25",
      maxWidth: "100%",
      minHeight: "9",
      minWidth: "0",
      px: "3",
      py: "2",
      transitionDuration: "slow",
      transitionProperty: "background-color, border-color, box-shadow, color, transform",
      transitionTimingFunction: "standard",
      textAlign: "center",
      whiteSpace: "normal",
      overflowWrap: "anywhere",
      _active: { transform: "translateY(0)" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: {
        backgroundColor: "surface.subtle",
        borderColor: "fg.muted",
        boxShadow: "xl",
        transform: "translateY(-1px)",
      },
    },
  },
  variants: {
    size: {
      sm: { content: { p: "3" }, header: { p: "3" }, footer: { p: "3" } },
      md: {},
      lg: { content: { p: "8" }, header: { p: "8" }, footer: { p: "8" } },
    },
  },
  defaultVariants: { size: "md" },
  staticCss: ["*"],
});
