import { defineSlotRecipe } from "@pandacss/dev";

export const tagsInputRecipe = defineSlotRecipe({
  className: "tagsInput",
  slots: [
    "root",
    "label",
    "control",
    "tagList",
    "tag",
    "tagLabel",
    "tagRemove",
    "input",
    "positioner",
    "list",
    "item",
    "empty",
  ],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      position: "relative",
      width: "100%",
    },
    label: {
      color: "fg.default",
      fontSize: "sm",
      fontWeight: "600",
    },
    control: {
      alignItems: "center",
      backgroundColor: "surface.canvas",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      display: "flex",
      flexWrap: "wrap",
      gap: "1",
      maxWidth: "100%",
      minWidth: "0",
      padding: "1",
      transitionDuration: "fast",
      transitionProperty: "border-color, box-shadow, background-color",
      transitionTimingFunction: "standard",
      _focusWithin: {
        borderColor: "accent.default",
        outline: "3px solid",
        outlineColor: "accent.default",
        outlineOffset: "0",
      },
      _disabled: {
        backgroundColor: "surface.subtle",
        cursor: "not-allowed",
        opacity: "0.65",
      },
    },
    tagList: {
      alignItems: "center",
      display: "flex",
      flexWrap: "wrap",
      gap: "1",
      maxWidth: "100%",
      minWidth: "0",
    },
    tag: {
      alignItems: "center",
      backgroundColor: "surface.subtle",
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      display: "inline-flex",
      gap: "1",
      maxWidth: "100%",
      minWidth: "0",
      px: "2",
      py: "1",
    },
    tagLabel: {
      fontSize: "sm",
      maxWidth: "100%",
      minWidth: "0",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    tagRemove: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "sm",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flex: "0 0 auto",
      fontFamily: "inherit",
      fontSize: "sm",
      justifyContent: "center",
      lineHeight: "1",
      minHeight: "6",
      minWidth: "6",
      p: "0",
      _hover: { backgroundColor: "surface.raised", color: "fg.default" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "1px",
      },
      _disabled: { cursor: "not-allowed" },
    },
    input: {
      backgroundColor: "transparent",
      border: "0",
      boxSizing: "border-box",
      color: "fg.default",
      flex: "1 1 8rem",
      fontFamily: "inherit",
      fontSize: "sm",
      minHeight: "9",
      minWidth: "6rem",
      outline: "none",
      padding: "2",
      maxWidth: "100%",
      _placeholder: { color: "fg.muted" },
      _disabled: { cursor: "not-allowed" },
    },
    positioner: {
      left: "0",
      position: "absolute",
      right: "0",
      top: "calc(100% + 0.25rem)",
      zIndex: "20",
    },
    list: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "lg",
      display: "flex",
      flexDirection: "column",
      gap: "1",
      maxHeight: "16rem",
      maxWidth: "100%",
      minWidth: "0",
      overflowY: "auto",
      p: "1",
    },
    item: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "md",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      fontFamily: "inherit",
      fontSize: "sm",
      justifyContent: "flex-start",
      maxWidth: "100%",
      minHeight: "9",
      minWidth: "0",
      overflowWrap: "anywhere",
      px: "3",
      py: "2",
      textAlign: "left",
      width: "100%",
      _hover: { backgroundColor: "surface.subtle" },
      _focusVisible: {
        backgroundColor: "surface.subtle",
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "-2px",
      },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    empty: { color: "fg.muted", fontSize: "sm", px: "3", py: "2" },
  },
  staticCss: ["*"],
});
