import { defineSlotRecipe } from "@pandacss/dev";

export const menubarRecipe = defineSlotRecipe({
  className: "menubar",
  slots: ["root", "trigger"],
  base: {
    root: {
      alignItems: "center",
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      display: "flex",
      gap: "1",
      boxSizing: "border-box",
      p: "1",
      maxWidth: "100%",
      minWidth: "0",
      width: "fit-content",
      flexWrap: "wrap",
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "lg",
      boxSizing: "border-box",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      justifyContent: "center",
      minHeight: "9",
      flexShrink: "1",
      maxWidth: "100%",
      minWidth: "0",
      px: "3",
      overflow: "hidden",
      overflowWrap: "anywhere",
      textOverflow: "ellipsis",
      whiteSpace: "normal",
      transitionDuration: "slow",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
      "&[data-popup-open]": { backgroundColor: "surface.subtle" },
    },
  },
  variants: {
    orientation: {
      horizontal: {
        root: { flexDirection: "row" },
        trigger: { width: "auto" },
      },
      vertical: {
        root: { alignItems: "stretch", flexDirection: "column" },
        trigger: { justifyContent: "flex-start", width: "100%" },
      },
    },
  },
  defaultVariants: { orientation: "horizontal" },
  staticCss: ["*"],
});
