import { defineSlotRecipe } from "@pandacss/dev";

export const commandRecipe = defineSlotRecipe({
  className: "command",
  slots: [
    "root",
    "input",
    "list",
    "group",
    "groupHeading",
    "item",
    "itemIndicator",
    "empty",
    "loading",
    "separator",
  ],
  base: {
    root: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      maxWidth: "100%",
      overflow: "hidden",
      width: "24rem",
    },
    input: {
      backgroundColor: "transparent",
      border: "0",
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      color: "fg.default",
      fontFamily: "inherit",
      fontSize: "sm",
      minHeight: "11",
      outline: "0",
      px: "3",
      width: "100%",
      _placeholder: { color: "fg.muted" },
      _focus: { boxShadow: "inset 0 -2px 0 accent.default" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    list: { maxHeight: "20rem", overflowY: "auto", p: "1" },
    group: { display: "flex", flexDirection: "column", gap: "1", p: "1" },
    groupHeading: { color: "fg.muted", fontSize: "xs", fontWeight: "700", px: "2", py: "1" },
    item: {
      alignItems: "center",
      borderRadius: "md",
      cursor: "pointer",
      display: "flex",
      fontSize: "sm",
      gap: "2",
      minHeight: "9",
      outline: "0",
      px: "2",
      py: "2",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      _hover: { backgroundColor: "surface.subtle" },
      "&[data-highlighted]": { backgroundColor: "accent.default", color: "fg.onAccent" },
      "&[data-disabled]": { cursor: "not-allowed", opacity: "0.5" },
    },
    itemIndicator: { color: "accent.default", marginInlineStart: "auto" },
    empty: { color: "fg.muted", fontSize: "sm", p: "4", textAlign: "center" },
    loading: { color: "fg.muted", fontSize: "sm", p: "4", textAlign: "center" },
    separator: { backgroundColor: "border.default", height: "1px", marginBlock: "1" },
  },
  staticCss: ["*"],
});
