import { defineSlotRecipe } from "@pandacss/dev";

export const commandRecipe = defineSlotRecipe({
  className: "command",
  slots: [
    "root",
    "input",
    "list",
    "group",
    "groupHeading",
    "item",
    "itemIndicator",
    "empty",
    "loading",
    "separator",
  ],
  base: {
    root: {
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      display: "flex",
      flexDirection: "column",
      minWidth: "0",
      overflow: "hidden",
      width: "100%",
      maxWidth: "24rem",
      _focusWithin: {
        borderColor: "accent.default",
        outlineColor: "focus",
        outlineOffset: "2px",
        outlineStyle: "solid",
        outlineWidth: "2px",
      },
    },
    input: {
      backgroundColor: "transparent",
      border: "0",
      borderBottomColor: "border.default",
      borderBottomStyle: "solid",
      borderBottomWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      display: "block",
      flexShrink: "0",
      fontFamily: "inherit",
      fontSize: "sm",
      minHeight: "11",
      minWidth: "0",
      outline: "0",
      overflow: "hidden",
      px: "3",
      textOverflow: "ellipsis",
      width: "100%",
      _placeholder: { color: "fg.muted" },
      _focus: { boxShadow: "none" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    list: {
      boxSizing: "border-box",
      maxHeight: "20rem",
      minWidth: "0",
      overflowX: "hidden",
      overflowY: "auto",
      overflowWrap: "anywhere",
      p: "1",
      width: "100%",
    },
    group: {
      display: "flex",
      flexDirection: "column",
      gap: "1",
      minWidth: "0",
      p: "1",
    },
    groupHeading: {
      color: "fg.muted",
      fontSize: "xs",
      fontWeight: "700",
      minWidth: "0",
      overflowWrap: "anywhere",
      px: "2",
      py: "1",
    },
    item: {
      alignItems: "center",
      borderRadius: "md",
      cursor: "pointer",
      display: "flex",
      fontSize: "sm",
      gap: "2",
      minHeight: "9",
      minWidth: "0",
      outline: "0",
      overflowWrap: "anywhere",
      px: "2",
      py: "2",
      transitionDuration: "fast",
      transitionProperty: "background-color, color",
      transitionTimingFunction: "standard",
      _hover: { backgroundColor: "surface.subtle" },
      "&[data-highlighted]": { backgroundColor: "accent.default", color: "fg.onAccent" },
      "&[data-disabled]": { cursor: "not-allowed", opacity: "0.5" },
    },
    itemIndicator: { color: "accent.default", marginInlineStart: "auto" },
    empty: { color: "fg.muted", fontSize: "sm", p: "4", textAlign: "center" },
    loading: { color: "fg.muted", fontSize: "sm", p: "4", textAlign: "center" },
    separator: {
      backgroundColor: "border.default",
      border: "0",
      display: "block",
      height: "1px",
      marginBlock: "1",
      marginInline: "0",
      width: "100%",
    },
  },
  variants: {
    mode: {
      default: {},
      dropdown: {
        root: {
          backgroundColor: "transparent",
          border: "0",
          borderRadius: "0",
          boxShadow: "none",
          position: "relative",
          overflow: "visible",
          _focusWithin: { borderColor: "transparent", boxShadow: "none", outline: "0" },
        },
        input: {
          backgroundColor: "surface.raised",
          borderColor: "border.default",
          borderStyle: "solid",
          borderWidth: "1px",
          borderRadius: "lg",
          boxShadow: "sm",
          _focus: {
            boxShadow: "none",
            outlineColor: "focus",
            outlineOffset: "0",
            outlineStyle: "solid",
            outlineWidth: "2px",
          },
        },
        list: {
          backgroundColor: "surface.raised",
          borderColor: "border.default",
          borderRadius: "lg",
          borderStyle: "solid",
          borderWidth: "1px",
          boxShadow: "lg",
          left: "0",
          maxWidth: "calc(100vw - 2rem)",
          position: "absolute",
          top: "calc(100% + 0.5rem)",
          width: "100%",
          zIndex: "50",
        },
      },
    },
  },
  defaultVariants: { mode: "default" },
  staticCss: ["*"],
});
