import { defineSlotRecipe } from "@pandacss/dev";

import { createBackdropBlurStyles } from "../../styles/backdrop";

export const figureRecipe = defineSlotRecipe({
  className: "figure",
  slots: [
    "root",
    "image",
    "caption",
    "trigger",
    "backdrop",
    "viewport",
    "popup",
    "lightboxImage",
    "lightboxCaption",
    "closeRow",
    "close",
    "title",
  ],
  base: {
    root: {
      display: "grid",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      m: "0",
    },
    image: {
      borderRadius: "xl",
      display: "block",
      maxWidth: "100%",
    },
    caption: {
      color: "fg.muted",
      fontSize: "sm",
      lineHeight: "1.5",
      minWidth: "0",
      overflowWrap: "anywhere",
    },
    trigger: {
      appearance: "none",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "xl",
      cursor: "zoom-in",
      display: "inline-flex",
      maxWidth: "100%",
      overflow: "hidden",
      p: "0",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "focus.ring",
        outlineOffset: "3px",
      },
    },
    backdrop: {
      ...createBackdropBlurStyles("md"),
      backgroundColor: "surface.overlay",
      inset: "0",
      minHeight: "100dvh",
      position: "fixed",
      zIndex: "60",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
    },
    viewport: {
      alignItems: "center",
      display: "flex",
      height: "100dvh",
      inset: "0",
      justifyContent: "center",
      overflow: "hidden",
      position: "fixed",
      width: "100vw",
      zIndex: "60",
    },
    popup: {
      alignItems: "center",
      backgroundColor: "transparent",
      display: "flex",
      flexDirection: "column",
      gap: "3",
      height: "100dvh",
      minWidth: "0",
      overflow: "hidden",
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      width: "100vw",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.98)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.98)" },
    },
    lightboxImage: {
      display: "block",
      flex: "1",
      minHeight: "0",
      maxHeight: "calc(100% - 6rem)",
      maxWidth: "100%",
      objectFit: "contain",
    },
    lightboxCaption: {
      backgroundColor: "surface.canvas",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      boxSizing: "border-box",
      color: "fg.default",
      fontSize: "sm",
      lineHeight: "1.5",
      maxHeight: "20vh",
      maxWidth: "min(48rem, calc(100% - 2rem))",
      overflowWrap: "anywhere",
      overflow: "hidden",
      p: "3",
      textAlign: "center",
      width: "100%",
    },
    closeRow: {
      alignItems: "center",
      display: "flex",
      flexShrink: "0",
      justifyContent: "flex-end",
      minHeight: "2rem",
      paddingInline: "1rem",
      width: "100%",
    },
    close: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      height: "8",
      justifyContent: "center",
      width: "8",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "focus.ring",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    title: {
      position: "absolute",
      width: "1px",
      height: "1px",
      overflow: "hidden",
      clip: "rect(0 0 0 0)",
      whiteSpace: "nowrap",
    },
  },
  staticCss: ["*"],
});
