import { defineSlotRecipe } from "@pandacss/dev";

export const figureRecipe = defineSlotRecipe({
  className: "figure",
  slots: [
    "root",
    "image",
    "caption",
    "trigger",
    "backdrop",
    "viewport",
    "popup",
    "lightboxImage",
    "lightboxCaption",
    "close",
    "title",
  ],
  base: {
    root: {
      display: "grid",
      gap: "2",
      maxWidth: "100%",
      minWidth: "0",
      m: "0",
    },
    image: {
      borderRadius: "xl",
      display: "block",
      maxWidth: "100%",
    },
    caption: {
      color: "fg.muted",
      fontSize: "sm",
      lineHeight: "1.5",
      minWidth: "0",
      overflowWrap: "anywhere",
    },
    trigger: {
      appearance: "none",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "xl",
      cursor: "zoom-in",
      display: "inline-flex",
      maxWidth: "100%",
      overflow: "hidden",
      p: "0",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "focus.ring",
        outlineOffset: "3px",
      },
    },
    backdrop: {
      backdropBlur: "md",
      backdropFilter: "auto",
      backgroundColor: "surface.overlay",
      inset: "0",
      minHeight: "100dvh",
      position: "fixed",
      zIndex: "60",
      "&[data-ending-style]": { opacity: "0" },
      "&[data-starting-style]": { opacity: "0" },
    },
    viewport: {
      alignItems: "center",
      display: "flex",
      inset: "0",
      justifyContent: "center",
      overflow: "auto",
      p: { base: "4", md: "8" },
      position: "fixed",
      zIndex: "60",
    },
    popup: {
      alignItems: "center",
      backgroundColor: "surface.canvas",
      borderColor: "border.default",
      borderRadius: "2xl",
      borderStyle: "solid",
      borderWidth: "1px",
      boxShadow: "xl",
      display: "flex",
      flexDirection: "column",
      gap: "3",
      maxHeight: "calc(100dvh - 2rem)",
      maxWidth: "calc(100vw - 2rem)",
      minWidth: "0",
      overflow: "auto",
      p: { base: "2", md: "3" },
      position: "relative",
      transitionDuration: "normal",
      transitionProperty: "opacity, transform",
      transitionTimingFunction: "standard",
      _motionReduce: { transitionDuration: "0ms", transitionProperty: "none" },
      "&[data-ending-style]": { opacity: "0", transform: "scale(0.98)" },
      "&[data-starting-style]": { opacity: "0", transform: "scale(0.98)" },
    },
    lightboxImage: {
      borderRadius: "xl",
      display: "block",
      maxHeight: "calc(100dvh - 8rem)",
      maxWidth: "calc(100vw - 4rem)",
      objectFit: "contain",
    },
    lightboxCaption: {
      color: "fg.default",
      fontSize: "sm",
      lineHeight: "1.5",
      maxWidth: "min(48rem, calc(100vw - 4rem))",
      overflowWrap: "anywhere",
      textAlign: "center",
    },
    close: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "full",
      borderStyle: "solid",
      borderWidth: "1px",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      height: "8",
      justifyContent: "center",
      position: "absolute",
      right: "3",
      top: "3",
      width: "8",
      zIndex: "1",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "focus.ring",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle" },
    },
    title: {
      position: "absolute",
      width: "1px",
      height: "1px",
      overflow: "hidden",
      clip: "rect(0 0 0 0)",
      whiteSpace: "nowrap",
    },
  },
  staticCss: ["*"],
});
