import { defineSlotRecipe } from "@pandacss/dev";

export const uploadRecipe = defineSlotRecipe({
  className: "upload",
  slots: [
    "root",
    "dropzone",
    "input",
    "trigger",
    "icon",
    "text",
    "hint",
    "preview",
    "progress",
    "progressTrack",
    "progressIndicator",
    "progressLabel",
    "list",
    "item",
    "itemName",
    "itemMeta",
    "remove",
    "error",
  ],
  base: {
    root: {
      display: "flex",
      flexDirection: "column",
      gap: "3",
      width: "100%",
    },
    dropzone: {
      alignItems: "center",
      backgroundColor: "surface.raised",
      borderColor: "border.default",
      borderRadius: "xl",
      borderStyle: "dashed",
      borderWidth: "2px",
      color: "fg.default",
      cursor: "pointer",
      display: "flex",
      flexDirection: "column",
      gap: "2",
      justifyContent: "center",
      minHeight: "32",
      outline: "none",
      p: "6",
      textAlign: "center",
      transitionDuration: "normal",
      transitionProperty: "background-color, border-color, box-shadow, color",
      transitionTimingFunction: "standard",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", borderColor: "border.strong" },
      _disabled: { cursor: "not-allowed", opacity: "0.55" },
    },
    input: {
      height: "1px",
      opacity: "0",
      overflow: "hidden",
      position: "absolute",
      width: "1px",
      clip: "rect(0 0 0 0)",
      whiteSpace: "nowrap",
    },
    trigger: {
      alignItems: "center",
      backgroundColor: "accent.default",
      border: "0",
      borderRadius: "lg",
      color: "fg.onAccent",
      cursor: "pointer",
      display: "inline-flex",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "700",
      gap: "2",
      justifyContent: "center",
      minHeight: "10",
      px: "4",
      py: "2",
      transitionDuration: "normal",
      transitionProperty: "background-color, box-shadow, transform",
      transitionTimingFunction: "standard",
      _active: { transform: "scale(0.98)" },
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "accent.hover", boxShadow: "md" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    icon: { color: "accent.default", fontSize: "2xl", lineHeight: "1" },
    text: {
      fontFamily: "system-ui, sans-serif",
      fontSize: "md",
      fontWeight: "700",
    },
    hint: {
      color: "fg.muted",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      lineHeight: "1.5",
    },
    preview: {
      alignItems: "center",
      backgroundColor: "surface.subtle",
      borderRadius: "md",
      color: "fg.muted",
      display: "inline-flex",
      flexShrink: "0",
      height: "12",
      justifyContent: "center",
      overflow: "hidden",
      width: "12",
      "& img": { height: "100%", objectFit: "cover", width: "100%" },
    },
    progress: {
      alignItems: "center",
      display: "flex",
      gap: "2",
      width: "100%",
    },
    progressTrack: {
      backgroundColor: "surface.subtle",
      borderRadius: "full",
      display: "block",
      flex: "1",
      height: "2",
      overflow: "hidden",
    },
    progressIndicator: {
      backgroundColor: "accent.default",
      borderRadius: "inherit",
      display: "block",
      height: "100%",
      transitionDuration: "normal",
      transitionProperty: "width",
      transitionTimingFunction: "standard",
      "&[data-indeterminate]": {
        animation: "jaciProgressIndeterminate 1.25s cubic-bezier(0.2, 0, 0, 1) infinite",
        width: "40%",
      },
    },
    progressLabel: {
      color: "fg.muted",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xs",
    },
    list: {
      display: "flex",
      flexDirection: "column",
      gap: "2",
      listStyleType: "none",
      margin: "0",
      padding: "0",
    },
    item: {
      alignItems: "center",
      backgroundColor: "surface.default",
      borderColor: "border.default",
      borderRadius: "lg",
      borderStyle: "solid",
      borderWidth: "1px",
      display: "flex",
      gap: "3",
      justifyContent: "space-between",
      minWidth: "0",
      p: "3",
    },
    itemName: {
      flex: "1",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      fontWeight: "600",
      minWidth: "0",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    itemMeta: {
      color: "fg.muted",
      flexShrink: "0",
      fontFamily: "system-ui, sans-serif",
      fontSize: "xs",
    },
    remove: {
      alignItems: "center",
      backgroundColor: "transparent",
      border: "0",
      borderRadius: "full",
      color: "fg.muted",
      cursor: "pointer",
      display: "inline-flex",
      flexShrink: "0",
      fontSize: "lg",
      height: "7",
      justifyContent: "center",
      width: "7",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      _hover: { backgroundColor: "surface.subtle", color: "fg.default" },
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    error: {
      color: "danger",
      fontFamily: "system-ui, sans-serif",
      fontSize: "sm",
      lineHeight: "1.5",
      margin: "0",
    },
  },
  variants: {
    disabled: {
      true: { dropzone: { cursor: "not-allowed", opacity: "0.55" } },
      false: {},
    },
    dropActive: {
      true: {
        dropzone: {
          backgroundColor: "surface.subtle",
          borderColor: "accent.default",
          boxShadow: "md",
          color: "accent.default",
        },
      },
      false: {},
    },
  },
  defaultVariants: { disabled: false, dropActive: false },
  staticCss: ["*"],
});
