import { defineSlotRecipe } from "@pandacss/dev";

export const checkboxGroupRecipe = defineSlotRecipe({
  className: "checkbox-group",
  slots: ["root", "label", "options", "option", "checkbox", "indicator"],
  base: {
    root: { display: "flex", flexDirection: "column", gap: "3", width: "100%" },
    label: { color: "fg.default", fontSize: "sm", fontWeight: "700", lineHeight: "1.5" },
    options: { display: "flex", flexDirection: "column", gap: "2" },
    option: {
      alignItems: "center",
      color: "fg.default",
      cursor: "pointer",
      display: "inline-flex",
      fontSize: "sm",
      gap: "2",
      width: "fit-content",
      _disabled: { cursor: "not-allowed", opacity: "0.5" },
    },
    checkbox: {
      alignItems: "center",
      appearance: "none",
      backgroundColor: "transparent",
      borderColor: "border.strong",
      borderRadius: "sm",
      borderStyle: "solid",
      borderWidth: "2px",
      display: "inline-flex",
      flexShrink: "0",
      height: "5",
      justifyContent: "center",
      width: "5",
      _focusVisible: {
        outline: "2px solid",
        outlineColor: "accent.default",
        outlineOffset: "2px",
      },
      "&[data-checked]": { borderColor: "accent.default" },
      "&[data-indeterminate]": { borderColor: "accent.default" },
      "&[data-disabled]": { cursor: "not-allowed", opacity: "0.5" },
    },
    indicator: {
      alignItems: "center",
      backgroundColor: "accent.default",
      color: "fg.onAccent",
      display: "inline-flex",
      fontSize: "xs",
      fontWeight: "700",
      height: "full",
      justifyContent: "center",
      lineHeight: "1",
      width: "full",
    },
  },
  staticCss: ["*"],
});
